package hibernate.merlin_hibernate.dao.Interface;

import java.util.List;

import hibernate.merlin_hibernate.entities.CompartmentsAnnotationPsortReportsHasCompartments;


public interface ICompartmentsAnnotationPsortReportsHasCompartmentsDAO {
	
	public void addCompartmentsAnnotationPsortReportsHasCompartment(CompartmentsAnnotationPsortReportsHasCompartments compartmentsAnnotationPsortReportsHasCompartment); 
	
	public void addCompartmentsAnnotationPsortReportsHasCompartments(List<CompartmentsAnnotationPsortReportsHasCompartments> compartmentsAnnotationPsortReportsHasCompartments); 
	
	public List<CompartmentsAnnotationPsortReportsHasCompartments> getAllCompartmentsAnnotationPsortReportsHasCompartments(); 
	
	public CompartmentsAnnotationPsortReportsHasCompartments getCompartmentsAnnotationPsortReportsHasCompartment(Integer id); 
	
	public void removeCompartmentsAnnotationPsortReportsHasCompartment(CompartmentsAnnotationPsortReportsHasCompartments compartmentsAnnotationPsortReportsHasCompartment); 
	
	public void removeCompartmentsAnnotationPsortReportsHasCompartments(List<CompartmentsAnnotationPsortReportsHasCompartments> compartmentsAnnotationPsortReportsHasCompartments); 
	
	public void updateCompartmentsAnnotationPsortReportsHasCompartments(List<CompartmentsAnnotationPsortReportsHasCompartments> compartmentsAnnotationPsortReportsHasCompartments); 
	
	public void updateCompartmentsAnnotationPsortReportsHasCompartment(CompartmentsAnnotationPsortReportsHasCompartments compartmentsAnnotationPsortReportsHasCompartment);
}
