package hibernate.merlin_hibernate.dao.Interface;

import java.util.List;

import hibernate.merlin_hibernate.entities.TransportersAnnotationTransportedMetabolitesDirections;


public interface ITransportersAnnotationTransportedMetabolitesDirectionsDAO {
	
	
	public void addTransportersAnnotationTransportedMetabolitesDirection(TransportersAnnotationTransportedMetabolitesDirections transportersAnnotationTransportedMetabolitesDirection); 
	
	public void addTransportersAnnotationTransportedMetabolitesDirections(List<TransportersAnnotationTransportedMetabolitesDirections> transportersAnnotationTransportedMetabolitesDirections); 
	
	public List<TransportersAnnotationTransportedMetabolitesDirections> getAllTransportersAnnotationTransportedMetabolitesDirections(); 
	
	public TransportersAnnotationTransportedMetabolitesDirections getTransportersAnnotationTransportedMetabolitesDirections(Integer id); 
	
	public void removeTransportersAnnotationTransportedMetabolitesDirection(TransportersAnnotationTransportedMetabolitesDirections transportersAnnotationTransportedMetabolitesDirection); 
	
	public void removeTransportersAnnotationTransportedMetabolitesDirections(List<TransportersAnnotationTransportedMetabolitesDirections> transportersAnnotationTransportedMetabolitesDirection); 
	
	public void updateTransportersAnnotationTransportedMetabolitesDirections(List<TransportersAnnotationTransportedMetabolitesDirections> transportersAnnotationTransportedMetabolitesDirection); 
	
	public void updateTransportersAnnotationTransportedMetabolitesDirection(TransportersAnnotationTransportedMetabolitesDirections transportersAnnotationTransportedMetabolitesDirection);

}
