package hibernate.merlin_hibernate.dao.Interface;

import java.util.List;

import hibernate.merlin_hibernate.entities.TransportersAnnotationGenesHasTcdbRegistries;



public interface ITransportersAnnotationGenesHasTcdbRegistriesDAO {
	
	public void addTransportersAnnotationGenesHasTcdbRegistry(TransportersAnnotationGenesHasTcdbRegistries transportersAnnotationGenesHasTcdbRegistry); 
	
	public void addTransportersAnnotationGenesHasTcdbRegistries(List<TransportersAnnotationGenesHasTcdbRegistries> transportersAnnotationGenesHasTcdbRegistries); 
	
	public List<TransportersAnnotationGenesHasTcdbRegistries> getAllTransportersAnnotationGenesHasTcdbRegistries(); 
	
	public TransportersAnnotationGenesHasTcdbRegistries getTransportersAnnotationGenesHasTcdbRegistry(Integer id); 
	
	public void removeTransportersAnnotationGenesHasTcdbRegistry(TransportersAnnotationGenesHasTcdbRegistries transportersAnnotationGenesHasTcdbRegistry); 
	
	public void removeTransportersAnnotationGenesHasTcdbRegistries(List<TransportersAnnotationGenesHasTcdbRegistries> transportersAnnotationGenesHasTcdbRegistries); 
	
	public void updateTransportersAnnotationGenesHasTcdbRegistries(List<TransportersAnnotationGenesHasTcdbRegistries> transportersAnnotationGenesHasTcdbRegistries); 
	
	public void updateTransportersAnnotationGenesHasTcdbRegistry(TransportersAnnotationGenesHasTcdbRegistries transportersAnnotationGenesHasTcdbRegistry);

}
