package hibernate.merlin_hibernate.dao.implementation;

import java.util.List;

import org.hibernate.SessionFactory;

import hibernate.merlin_hibernate.entities.TransportersAnnotationTcNumbersHasTransportSystems;
import hibernate.merlin_hibernate.dao.Interface.ITransportersAnnotationTcNumbersHasTransportSystemsDAO;


public class TransportersAnnotationTcNumbersHasTransportSystemsDAOImpl extends GenericDaoImpl<TransportersAnnotationTcNumbersHasTransportSystems> implements ITransportersAnnotationTcNumbersHasTransportSystemsDAO{

	public TransportersAnnotationTcNumbersHasTransportSystemsDAOImpl(SessionFactory sessionFactory) {
		super(sessionFactory, TransportersAnnotationTcNumbersHasTransportSystems.class);
	
	}

	public void addTransportersAnnotationTcNumbersHasTransportSystem(TransportersAnnotationTcNumbersHasTransportSystems transportersAnnotationTcNumbersHasTransportSystem) {
		super.save(transportersAnnotationTcNumbersHasTransportSystem);
	}

	public void addTransportersAnnotationTcNumbersHasTransportSystems(List<TransportersAnnotationTcNumbersHasTransportSystems> transportersAnnotationTcNumbersHasTransportSystems) {
		for (TransportersAnnotationTcNumbersHasTransportSystems transportersAnnotationTcNumbersHasTransportSystem: transportersAnnotationTcNumbersHasTransportSystems) {
			this.addTransportersAnnotationTcNumbersHasTransportSystem(transportersAnnotationTcNumbersHasTransportSystem);
		}
		
	}

	public List<TransportersAnnotationTcNumbersHasTransportSystems> getAllTransportersAnnotationTcNumbersHasTransportSystems() {
		return super.findAll();
	}

	public TransportersAnnotationTcNumbersHasTransportSystems getTransportersAnnotationTcNumbersHasTransportSystems(Integer id) {
		return super.findById(id);
	}

	public void removeTransportersAnnotationTcNumbersHasTransportSystem(TransportersAnnotationTcNumbersHasTransportSystems transportersAnnotationTcNumbersHasTransportSystem) {
		super.delete(transportersAnnotationTcNumbersHasTransportSystem);
		
	}

	public void removeTransportersAnnotationTcNumbersHasTransportSystems(List<TransportersAnnotationTcNumbersHasTransportSystems> transportersAnnotationTcNumbersHasTransportSystems) {
		for (TransportersAnnotationTcNumbersHasTransportSystems transportersAnnotationTcNumbersHasTransportSystem: transportersAnnotationTcNumbersHasTransportSystems) {
			this.removeTransportersAnnotationTcNumbersHasTransportSystem(transportersAnnotationTcNumbersHasTransportSystem);
		}
		
	}

	public void updateTransportersAnnotationTcNumbersHasTransportSystems(List<TransportersAnnotationTcNumbersHasTransportSystems> transportersAnnotationTcNumbersHasTransportSystems) {
		for (TransportersAnnotationTcNumbersHasTransportSystems transportersAnnotationTcNumbersHasTransportSystem: transportersAnnotationTcNumbersHasTransportSystems) {
			this.update(transportersAnnotationTcNumbersHasTransportSystem);
		}
		
		
	}

	public void updateTransportersAnnotationTcNumbersHasTransportSystem(TransportersAnnotationTcNumbersHasTransportSystems TransportersAnnotationTcNumbersHasTransportSystem) {
		super.update(TransportersAnnotationTcNumbersHasTransportSystem);
		
	}

}
