package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompartmentsAnnotationCompartments generated by hbm2java
 */
@Entity
@Table(name = "compartments_annotation_compartments", catalog = "sysbio_model")
public class CompartmentsAnnotationCompartments implements java.io.Serializable {

	private Integer id;
	private String name;
	private String abbreviation;
	private Set<CompartmentsAnnotationPsortReportsHasCompartments> compartmentsAnnotationPsortReportsHasCompartmentses = new HashSet<CompartmentsAnnotationPsortReportsHasCompartments>(
			0);

	public CompartmentsAnnotationCompartments() {
	}

	public CompartmentsAnnotationCompartments(String name, String abbreviation,
			Set<CompartmentsAnnotationPsortReportsHasCompartments> compartmentsAnnotationPsortReportsHasCompartmentses) {
		this.name = name;
		this.abbreviation = abbreviation;
		this.compartmentsAnnotationPsortReportsHasCompartmentses = compartmentsAnnotationPsortReportsHasCompartmentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "abbreviation", length = 10)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compartmentsAnnotationCompartments")
	public Set<CompartmentsAnnotationPsortReportsHasCompartments> getCompartmentsAnnotationPsortReportsHasCompartmentses() {
		return this.compartmentsAnnotationPsortReportsHasCompartmentses;
	}

	public void setCompartmentsAnnotationPsortReportsHasCompartmentses(
			Set<CompartmentsAnnotationPsortReportsHasCompartments> compartmentsAnnotationPsortReportsHasCompartmentses) {
		this.compartmentsAnnotationPsortReportsHasCompartmentses = compartmentsAnnotationPsortReportsHasCompartmentses;
	}

}
