package hibernate.merlin_hibernate.Entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnzymesAnnotationHomologuesHasEcnumber generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_homologues_has_ecnumber", catalog = "merlin_basic2")
public class EnzymesAnnotationHomologuesHasEcnumber implements java.io.Serializable {

	private EnzymesAnnotationHomologuesHasEcnumberId id;

	public EnzymesAnnotationHomologuesHasEcnumber() {
	}

	public EnzymesAnnotationHomologuesHasEcnumber(EnzymesAnnotationHomologuesHasEcnumberId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "homologuesSKey", column = @Column(name = "homologues_s_key", nullable = false)),
			@AttributeOverride(name = "ecNumberSKey", column = @Column(name = "ecNumber_s_key", nullable = false)) })
	public EnzymesAnnotationHomologuesHasEcnumberId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationHomologuesHasEcnumberId id) {
		this.id = id;
	}

}
