package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumber generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecnumber", catalog = "sysbio_model")
public class EnzymesAnnotationEcnumber implements java.io.Serializable {

	private Integer SKey;
	private String ecNumber;
	private Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses = new HashSet<EnzymesAnnotationHomologues>(
			0);

	public EnzymesAnnotationEcnumber() {
	}

	public EnzymesAnnotationEcnumber(String ecNumber, Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses) {
		this.ecNumber = ecNumber;
		this.enzymesAnnotationHomologueses = enzymesAnnotationHomologueses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "s_key", unique = true, nullable = false)
	public Integer getSKey() {
		return this.SKey;
	}

	public void setSKey(Integer SKey) {
		this.SKey = SKey;
	}

	@Column(name = "ecNumber", length = 16777215)
	public String getEcNumber() {
		return this.ecNumber;
	}

	public void setEcNumber(String ecNumber) {
		this.ecNumber = ecNumber;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "enzymes_annotation_homologues_has_ecnumber", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "ecNumber_s_key", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "homologues_s_key", nullable = false, updatable = false) })
	public Set<EnzymesAnnotationHomologues> getEnzymesAnnotationHomologueses() {
		return this.enzymesAnnotationHomologueses;
	}

	public void setEnzymesAnnotationHomologueses(Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses) {
		this.enzymesAnnotationHomologueses = enzymesAnnotationHomologueses;
	}

}
