package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnzymesAnnotationProductrankHasOrganism generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_productrank_has_organism", catalog = "test_hibernate")
public class EnzymesAnnotationProductrankHasOrganism implements java.io.Serializable {

	private EnzymesAnnotationProductrankHasOrganismId id;
	private EnzymesAnnotationOrganism enzymesAnnotationOrganism;
	private EnzymesAnnotationProductrank enzymesAnnotationProductrank;

	public EnzymesAnnotationProductrankHasOrganism() {
	}

	public EnzymesAnnotationProductrankHasOrganism(EnzymesAnnotationProductrankHasOrganismId id,
			EnzymesAnnotationOrganism enzymesAnnotationOrganism,
			EnzymesAnnotationProductrank enzymesAnnotationProductrank) {
		this.id = id;
		this.enzymesAnnotationOrganism = enzymesAnnotationOrganism;
		this.enzymesAnnotationProductrank = enzymesAnnotationProductrank;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productRankSKey", column = @Column(name = "productRank_s_key", nullable = false)),
			@AttributeOverride(name = "organismSKey", column = @Column(name = "organism_s_key", nullable = false)) })
	public EnzymesAnnotationProductrankHasOrganismId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationProductrankHasOrganismId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organism_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationOrganism getEnzymesAnnotationOrganism() {
		return this.enzymesAnnotationOrganism;
	}

	public void setEnzymesAnnotationOrganism(EnzymesAnnotationOrganism enzymesAnnotationOrganism) {
		this.enzymesAnnotationOrganism = enzymesAnnotationOrganism;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productRank_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationProductrank getEnzymesAnnotationProductrank() {
		return this.enzymesAnnotationProductrank;
	}

	public void setEnzymesAnnotationProductrank(EnzymesAnnotationProductrank enzymesAnnotationProductrank) {
		this.enzymesAnnotationProductrank = enzymesAnnotationProductrank;
	}

}
