package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnzymesAnnotationFastasequence generated by hbm2java
 */
@Entity
@Table(name="enzymes_annotation_fastasequence"
    ,catalog="test_hibernate"
)
public class EnzymesAnnotationFastasequence  implements java.io.Serializable {


     private EnzymesAnnotationFastasequenceId id;
     private String sequence;

    public EnzymesAnnotationFastasequence() {
    }

	
    public EnzymesAnnotationFastasequence(EnzymesAnnotationFastasequenceId id) {
        this.id = id;
    }
    public EnzymesAnnotationFastasequence(EnzymesAnnotationFastasequenceId id, String sequence) {
       this.id = id;
       this.sequence = sequence;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="SKey", column=@Column(name="s_key", nullable=false) ), 
        @AttributeOverride(name="geneHomologySKey", column=@Column(name="geneHomology_s_key", nullable=false) ) } )
    public EnzymesAnnotationFastasequenceId getId() {
        return this.id;
    }
    
    public void setId(EnzymesAnnotationFastasequenceId id) {
        this.id = id;
    }

    
    @Column(name="sequence", length=65535)
    public String getSequence() {
        return this.sequence;
    }
    
    public void setSequence(String sequence) {
        this.sequence = sequence;
    }




}


