package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EnzymesAnnotationOrganism generated by hbm2java
 */
@Entity
@Table(name="enzymes_annotation_organism"
    ,catalog="test_hibernate"
)
public class EnzymesAnnotationOrganism  implements java.io.Serializable {


     private Integer SKey;
     private String organism;
     private String taxonomy;
     private Integer taxRank;

    public EnzymesAnnotationOrganism() {
    }

    public EnzymesAnnotationOrganism(String organism, String taxonomy, Integer taxRank) {
       this.organism = organism;
       this.taxonomy = taxonomy;
       this.taxRank = taxRank;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="s_key", unique=true, nullable=false)
    public Integer getSKey() {
        return this.SKey;
    }
    
    public void setSKey(Integer SKey) {
        this.SKey = SKey;
    }

    
    @Column(name="organism", length=200)
    public String getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(String organism) {
        this.organism = organism;
    }

    
    @Column(name="taxonomy", length=65535)
    public String getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(String taxonomy) {
        this.taxonomy = taxonomy;
    }

    
    @Column(name="taxRank")
    public Integer getTaxRank() {
        return this.taxRank;
    }
    
    public void setTaxRank(Integer taxRank) {
        this.taxRank = taxRank;
    }




}


