package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumberlist generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecnumberlist", catalog = "sysbio_model")
public class EnzymesAnnotationEcnumberlist implements java.io.Serializable {

	private Integer SKey;
	private EnzymesAnnotationHomologydata enzymesAnnotationHomologydata;
	private String otherEcnumbers;

	public EnzymesAnnotationEcnumberlist() {
	}

	public EnzymesAnnotationEcnumberlist(EnzymesAnnotationHomologydata enzymesAnnotationHomologydata) {
		this.enzymesAnnotationHomologydata = enzymesAnnotationHomologydata;
	}

	public EnzymesAnnotationEcnumberlist(EnzymesAnnotationHomologydata enzymesAnnotationHomologydata,
			String otherEcnumbers) {
		this.enzymesAnnotationHomologydata = enzymesAnnotationHomologydata;
		this.otherEcnumbers = otherEcnumbers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "s_key", unique = true, nullable = false)
	public Integer getSKey() {
		return this.SKey;
	}

	public void setSKey(Integer SKey) {
		this.SKey = SKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homologyData_s_key", nullable = false)
	public EnzymesAnnotationHomologydata getEnzymesAnnotationHomologydata() {
		return this.enzymesAnnotationHomologydata;
	}

	public void setEnzymesAnnotationHomologydata(EnzymesAnnotationHomologydata enzymesAnnotationHomologydata) {
		this.enzymesAnnotationHomologydata = enzymesAnnotationHomologydata;
	}

	@Column(name = "otherECNumbers", length = 16777215)
	public String getOtherEcnumbers() {
		return this.otherEcnumbers;
	}

	public void setOtherEcnumbers(String otherEcnumbers) {
		this.otherEcnumbers = otherEcnumbers;
	}

}
