package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumberrank generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecnumberrank", catalog = "test_hibernate")
public class EnzymesAnnotationEcnumberrank implements java.io.Serializable {

	private EnzymesAnnotationEcnumberrankId id;
	private EnzymesAnnotationGenehomology enzymesAnnotationGenehomology;
	private String ecNumber;
	private Integer rank;
	private Set<EnzymesAnnotationEcnumberrankHasOrganism> enzymesAnnotationEcnumberrankHasOrganisms = new HashSet<EnzymesAnnotationEcnumberrankHasOrganism>(
			0);

	public EnzymesAnnotationEcnumberrank() {
	}

	public EnzymesAnnotationEcnumberrank(EnzymesAnnotationEcnumberrankId id,
			EnzymesAnnotationGenehomology enzymesAnnotationGenehomology) {
		this.id = id;
		this.enzymesAnnotationGenehomology = enzymesAnnotationGenehomology;
	}

	public EnzymesAnnotationEcnumberrank(EnzymesAnnotationEcnumberrankId id,
			EnzymesAnnotationGenehomology enzymesAnnotationGenehomology, String ecNumber, Integer rank,
			Set<EnzymesAnnotationEcnumberrankHasOrganism> enzymesAnnotationEcnumberrankHasOrganisms) {
		this.id = id;
		this.enzymesAnnotationGenehomology = enzymesAnnotationGenehomology;
		this.ecNumber = ecNumber;
		this.rank = rank;
		this.enzymesAnnotationEcnumberrankHasOrganisms = enzymesAnnotationEcnumberrankHasOrganisms;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "SKey", column = @Column(name = "s_key", nullable = false)),
			@AttributeOverride(name = "geneHomologySKey", column = @Column(name = "geneHomology_s_key", nullable = false)) })
	public EnzymesAnnotationEcnumberrankId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationEcnumberrankId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "geneHomology_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationGenehomology getEnzymesAnnotationGenehomology() {
		return this.enzymesAnnotationGenehomology;
	}

	public void setEnzymesAnnotationGenehomology(EnzymesAnnotationGenehomology enzymesAnnotationGenehomology) {
		this.enzymesAnnotationGenehomology = enzymesAnnotationGenehomology;
	}

	@Column(name = "ecNumber", length = 16777215)
	public String getEcNumber() {
		return this.ecNumber;
	}

	public void setEcNumber(String ecNumber) {
		this.ecNumber = ecNumber;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationEcnumberrank")
	public Set<EnzymesAnnotationEcnumberrankHasOrganism> getEnzymesAnnotationEcnumberrankHasOrganisms() {
		return this.enzymesAnnotationEcnumberrankHasOrganisms;
	}

	public void setEnzymesAnnotationEcnumberrankHasOrganisms(
			Set<EnzymesAnnotationEcnumberrankHasOrganism> enzymesAnnotationEcnumberrankHasOrganisms) {
		this.enzymesAnnotationEcnumberrankHasOrganisms = enzymesAnnotationEcnumberrankHasOrganisms;
	}

}
