package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnzymesAnnotationEcnumberrankHasOrganism generated by hbm2java
 */
@Entity
@Table(name="enzymes_annotation_ecnumberrank_has_organism"
    ,catalog="test_hibernate"
)
public class EnzymesAnnotationEcnumberrankHasOrganism  implements java.io.Serializable {


     private EnzymesAnnotationEcnumberrankHasOrganismId id;

    public EnzymesAnnotationEcnumberrankHasOrganism() {
    }

    public EnzymesAnnotationEcnumberrankHasOrganism(EnzymesAnnotationEcnumberrankHasOrganismId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ecNumberRankSKey", column=@Column(name="ecNumberRank_s_key", nullable=false) ), 
        @AttributeOverride(name="organismSKey", column=@Column(name="organism_s_key", nullable=false) ) } )
    public EnzymesAnnotationEcnumberrankHasOrganismId getId() {
        return this.id;
    }
    
    public void setId(EnzymesAnnotationEcnumberrankHasOrganismId id) {
        this.id = id;
    }




}


