package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnzymesAnnotationOrganism generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_organism", catalog = "test_hibernate")
public class EnzymesAnnotationOrganism implements java.io.Serializable {

	private Integer SKey;
	private String organism;
	private String taxonomy;
	private Integer taxRank;
	private Set<EnzymesAnnotationProductrankHasOrganism> enzymesAnnotationProductrankHasOrganisms = new HashSet<EnzymesAnnotationProductrankHasOrganism>(
			0);
	private Set<EnzymesAnnotationEcnumberrankHasOrganism> enzymesAnnotationEcnumberrankHasOrganisms = new HashSet<EnzymesAnnotationEcnumberrankHasOrganism>(
			0);
	private Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses = new HashSet<EnzymesAnnotationHomologues>(
			0);

	public EnzymesAnnotationOrganism() {
	}

	public EnzymesAnnotationOrganism(String organism, String taxonomy, Integer taxRank,
			Set<EnzymesAnnotationProductrankHasOrganism> enzymesAnnotationProductrankHasOrganisms,
			Set<EnzymesAnnotationEcnumberrankHasOrganism> enzymesAnnotationEcnumberrankHasOrganisms,
			Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses) {
		this.organism = organism;
		this.taxonomy = taxonomy;
		this.taxRank = taxRank;
		this.enzymesAnnotationProductrankHasOrganisms = enzymesAnnotationProductrankHasOrganisms;
		this.enzymesAnnotationEcnumberrankHasOrganisms = enzymesAnnotationEcnumberrankHasOrganisms;
		this.enzymesAnnotationHomologueses = enzymesAnnotationHomologueses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "s_key", unique = true, nullable = false)
	public Integer getSKey() {
		return this.SKey;
	}

	public void setSKey(Integer SKey) {
		this.SKey = SKey;
	}

	@Column(name = "organism", length = 200)
	public String getOrganism() {
		return this.organism;
	}

	public void setOrganism(String organism) {
		this.organism = organism;
	}

	@Column(name = "taxonomy", length = 65535)
	public String getTaxonomy() {
		return this.taxonomy;
	}

	public void setTaxonomy(String taxonomy) {
		this.taxonomy = taxonomy;
	}

	@Column(name = "taxRank")
	public Integer getTaxRank() {
		return this.taxRank;
	}

	public void setTaxRank(Integer taxRank) {
		this.taxRank = taxRank;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationOrganism")
	public Set<EnzymesAnnotationProductrankHasOrganism> getEnzymesAnnotationProductrankHasOrganisms() {
		return this.enzymesAnnotationProductrankHasOrganisms;
	}

	public void setEnzymesAnnotationProductrankHasOrganisms(
			Set<EnzymesAnnotationProductrankHasOrganism> enzymesAnnotationProductrankHasOrganisms) {
		this.enzymesAnnotationProductrankHasOrganisms = enzymesAnnotationProductrankHasOrganisms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationOrganism")
	public Set<EnzymesAnnotationEcnumberrankHasOrganism> getEnzymesAnnotationEcnumberrankHasOrganisms() {
		return this.enzymesAnnotationEcnumberrankHasOrganisms;
	}

	public void setEnzymesAnnotationEcnumberrankHasOrganisms(
			Set<EnzymesAnnotationEcnumberrankHasOrganism> enzymesAnnotationEcnumberrankHasOrganisms) {
		this.enzymesAnnotationEcnumberrankHasOrganisms = enzymesAnnotationEcnumberrankHasOrganisms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationOrganism")
	public Set<EnzymesAnnotationHomologues> getEnzymesAnnotationHomologueses() {
		return this.enzymesAnnotationHomologueses;
	}

	public void setEnzymesAnnotationHomologueses(Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses) {
		this.enzymesAnnotationHomologueses = enzymesAnnotationHomologueses;
	}

}
