package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * InterproInterproModel generated by hbm2java
 */
@Entity
@Table(name="interpro_interpro_model"
    ,catalog="test_hibernate"
)
public class InterproInterproModel  implements java.io.Serializable {


     private String accession;
     private String description;
     private String name;
     private Set<InterproInterproResult> interproInterproResults = new HashSet<InterproInterproResult>(0);

    public InterproInterproModel() {
    }

	
    public InterproInterproModel(String accession) {
        this.accession = accession;
    }
    public InterproInterproModel(String accession, String description, String name, Set<InterproInterproResult> interproInterproResults) {
       this.accession = accession;
       this.description = description;
       this.name = name;
       this.interproInterproResults = interproInterproResults;
    }
   
     @Id 

    
    @Column(name="accession", unique=true, nullable=false, length=45)
    public String getAccession() {
        return this.accession;
    }
    
    public void setAccession(String accession) {
        this.accession = accession;
    }

    
    @Column(name="description", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="interpro_interpro_result_has_model", catalog="test_hibernate", joinColumns = { 
        @JoinColumn(name="model_accession", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="result_id", nullable=false, updatable=false) })
    public Set<InterproInterproResult> getInterproInterproResults() {
        return this.interproInterproResults;
    }
    
    public void setInterproInterproResults(Set<InterproInterproResult> interproInterproResults) {
        this.interproInterproResults = interproInterproResults;
    }




}


