package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InterproInterproEntry generated by hbm2java
 */
@Entity
@Table(name = "interpro_interpro_entry", catalog = "test_hibernate")
public class InterproInterproEntry implements java.io.Serializable {

	private Integer id;
	private String accession;
	private String description;
	private String name;
	private String type;
	private Set<InterproInterproXref> interproInterproXrefs = new HashSet<InterproInterproXref>(0);
	private Set<InterproInterproResult> interproInterproResults = new HashSet<InterproInterproResult>(0);

	public InterproInterproEntry() {
	}

	public InterproInterproEntry(String accession, String description, String name, String type) {
		this.accession = accession;
		this.description = description;
		this.name = name;
		this.type = type;
	}

	public InterproInterproEntry(String accession, String description, String name, String type,
			Set<InterproInterproXref> interproInterproXrefs, Set<InterproInterproResult> interproInterproResults) {
		this.accession = accession;
		this.description = description;
		this.name = name;
		this.type = type;
		this.interproInterproXrefs = interproInterproXrefs;
		this.interproInterproResults = interproInterproResults;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "accession", nullable = false, length = 45)
	public String getAccession() {
		return this.accession;
	}

	public void setAccession(String accession) {
		this.accession = accession;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interproInterproEntry")
	public Set<InterproInterproXref> getInterproInterproXrefs() {
		return this.interproInterproXrefs;
	}

	public void setInterproInterproXrefs(Set<InterproInterproXref> interproInterproXrefs) {
		this.interproInterproXrefs = interproInterproXrefs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "interpro_interpro_result_has_entry", catalog = "test_hibernate", joinColumns = {
			@JoinColumn(name = "entry_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "result_id", nullable = false, updatable = false) })
	public Set<InterproInterproResult> getInterproInterproResults() {
		return this.interproInterproResults;
	}

	public void setInterproInterproResults(Set<InterproInterproResult> interproInterproResults) {
		this.interproInterproResults = interproInterproResults;
	}

}
