package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InterproInterproLocation generated by hbm2java
 */
@Entity
@Table(name = "interpro_interpro_location", catalog = "sysbio_model")
public class InterproInterproLocation implements java.io.Serializable {

	private Integer id;
	private InterproInterproResult interproInterproResult;
	private int start;
	private int end;
	private Float score;
	private Integer hmmStart;
	private Integer hmmEnd;
	private Float evalue;
	private Integer envStart;
	private Integer envEnd;
	private Integer hmmLength;

	public InterproInterproLocation() {
	}

	public InterproInterproLocation(InterproInterproResult interproInterproResult, int start, int end) {
		this.interproInterproResult = interproInterproResult;
		this.start = start;
		this.end = end;
	}

	public InterproInterproLocation(InterproInterproResult interproInterproResult, int start, int end, Float score,
			Integer hmmStart, Integer hmmEnd, Float evalue, Integer envStart, Integer envEnd, Integer hmmLength) {
		this.interproInterproResult = interproInterproResult;
		this.start = start;
		this.end = end;
		this.score = score;
		this.hmmStart = hmmStart;
		this.hmmEnd = hmmEnd;
		this.evalue = evalue;
		this.envStart = envStart;
		this.envEnd = envEnd;
		this.hmmLength = hmmLength;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "result_id", nullable = false)
	public InterproInterproResult getInterproInterproResult() {
		return this.interproInterproResult;
	}

	public void setInterproInterproResult(InterproInterproResult interproInterproResult) {
		this.interproInterproResult = interproInterproResult;
	}

	@Column(name = "start", nullable = false)
	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false)
	public int getEnd() {
		return this.end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

	@Column(name = "score", precision = 12, scale = 0)
	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	@Column(name = "hmmStart")
	public Integer getHmmStart() {
		return this.hmmStart;
	}

	public void setHmmStart(Integer hmmStart) {
		this.hmmStart = hmmStart;
	}

	@Column(name = "hmmEnd")
	public Integer getHmmEnd() {
		return this.hmmEnd;
	}

	public void setHmmEnd(Integer hmmEnd) {
		this.hmmEnd = hmmEnd;
	}

	@Column(name = "eValue", precision = 12, scale = 0)
	public Float getEvalue() {
		return this.evalue;
	}

	public void setEvalue(Float evalue) {
		this.evalue = evalue;
	}

	@Column(name = "envStart")
	public Integer getEnvStart() {
		return this.envStart;
	}

	public void setEnvStart(Integer envStart) {
		this.envStart = envStart;
	}

	@Column(name = "envEnd")
	public Integer getEnvEnd() {
		return this.envEnd;
	}

	public void setEnvEnd(Integer envEnd) {
		this.envEnd = envEnd;
	}

	@Column(name = "hmmLength")
	public Integer getHmmLength() {
		return this.hmmLength;
	}

	public void setHmmLength(Integer hmmLength) {
		this.hmmLength = hmmLength;
	}

}
