package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InterproInterproResult generated by hbm2java
 */
@Entity
@Table(name = "interpro_interpro_result", catalog = "sysbio_model")
public class InterproInterproResult implements java.io.Serializable {

	private Integer id;
	private InterproInterproResults interproInterproResults;
	private String tool;
	private Float evalue;
	private Float score;
	private String familyName;
	private String accession;
	private String name;
	private String ec;
	private String goName;
	private String localization;
	private String database;
	private Set<InterproInterproEntry> interproInterproEntries = new HashSet<InterproInterproEntry>(0);
	private Set<InterproInterproLocation> interproInterproLocations = new HashSet<InterproInterproLocation>(0);
	private Set<InterproInterproModel> interproInterproModels = new HashSet<InterproInterproModel>(0);

	public InterproInterproResult() {
	}

	public InterproInterproResult(InterproInterproResults interproInterproResults, String tool) {
		this.interproInterproResults = interproInterproResults;
		this.tool = tool;
	}

	public InterproInterproResult(InterproInterproResults interproInterproResults, String tool, Float evalue,
			Float score, String familyName, String accession, String name, String ec, String goName,
			String localization, String database, Set<InterproInterproEntry> interproInterproEntries,
			Set<InterproInterproLocation> interproInterproLocations,
			Set<InterproInterproModel> interproInterproModels) {
		this.interproInterproResults = interproInterproResults;
		this.tool = tool;
		this.evalue = evalue;
		this.score = score;
		this.familyName = familyName;
		this.accession = accession;
		this.name = name;
		this.ec = ec;
		this.goName = goName;
		this.localization = localization;
		this.database = database;
		this.interproInterproEntries = interproInterproEntries;
		this.interproInterproLocations = interproInterproLocations;
		this.interproInterproModels = interproInterproModels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "results_id", nullable = false)
	public InterproInterproResults getInterproInterproResults() {
		return this.interproInterproResults;
	}

	public void setInterproInterproResults(InterproInterproResults interproInterproResults) {
		this.interproInterproResults = interproInterproResults;
	}

	@Column(name = "tool", nullable = false, length = 250)
	public String getTool() {
		return this.tool;
	}

	public void setTool(String tool) {
		this.tool = tool;
	}

	@Column(name = "eValue", precision = 12, scale = 0)
	public Float getEvalue() {
		return this.evalue;
	}

	public void setEvalue(Float evalue) {
		this.evalue = evalue;
	}

	@Column(name = "score", precision = 12, scale = 0)
	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	@Column(name = "familyName", length = 45)
	public String getFamilyName() {
		return this.familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	@Column(name = "accession", length = 45)
	public String getAccession() {
		return this.accession;
	}

	public void setAccession(String accession) {
		this.accession = accession;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ec", length = 45)
	public String getEc() {
		return this.ec;
	}

	public void setEc(String ec) {
		this.ec = ec;
	}

	@Column(name = "goName", length = 250)
	public String getGoName() {
		return this.goName;
	}

	public void setGoName(String goName) {
		this.goName = goName;
	}

	@Column(name = "localization", length = 45)
	public String getLocalization() {
		return this.localization;
	}

	public void setLocalization(String localization) {
		this.localization = localization;
	}

	@Column(name = "database", length = 45)
	public String getDatabase() {
		return this.database;
	}

	public void setDatabase(String database) {
		this.database = database;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "interpro_interpro_result_has_entry", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "result_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "entry_id", nullable = false, updatable = false) })
	public Set<InterproInterproEntry> getInterproInterproEntries() {
		return this.interproInterproEntries;
	}

	public void setInterproInterproEntries(Set<InterproInterproEntry> interproInterproEntries) {
		this.interproInterproEntries = interproInterproEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interproInterproResult")
	public Set<InterproInterproLocation> getInterproInterproLocations() {
		return this.interproInterproLocations;
	}

	public void setInterproInterproLocations(Set<InterproInterproLocation> interproInterproLocations) {
		this.interproInterproLocations = interproInterproLocations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "interpro_interpro_result_has_model", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "result_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "model_accession", nullable = false, updatable = false) })
	public Set<InterproInterproModel> getInterproInterproModels() {
		return this.interproInterproModels;
	}

	public void setInterproInterproModels(Set<InterproInterproModel> interproInterproModels) {
		this.interproInterproModels = interproInterproModels;
	}

}
