package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InterproInterproXref generated by hbm2java
 */
@Entity
@Table(name="interpro_interpro_xref"
    ,catalog="test_hibernate"
)
public class InterproInterproXref  implements java.io.Serializable {


     private Integer id;
     private InterproInterproEntry interproInterproEntry;
     private String category;
     private String database;
     private String name;
     private String externalId;

    public InterproInterproXref() {
    }

	
    public InterproInterproXref(InterproInterproEntry interproInterproEntry, String database, String name) {
        this.interproInterproEntry = interproInterproEntry;
        this.database = database;
        this.name = name;
    }
    public InterproInterproXref(InterproInterproEntry interproInterproEntry, String category, String database, String name, String externalId) {
       this.interproInterproEntry = interproInterproEntry;
       this.category = category;
       this.database = database;
       this.name = name;
       this.externalId = externalId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entry_id", nullable=false)
    public InterproInterproEntry getInterproInterproEntry() {
        return this.interproInterproEntry;
    }
    
    public void setInterproInterproEntry(InterproInterproEntry interproInterproEntry) {
        this.interproInterproEntry = interproInterproEntry;
    }

    
    @Column(name="category", length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="database", nullable=false, length=45)
    public String getDatabase() {
        return this.database;
    }
    
    public void setDatabase(String database) {
        this.database = database;
    }

    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="external_id", length=45)
    public String getExternalId() {
        return this.externalId;
    }
    
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }




}


