package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelSuperpathway generated by hbm2java
 */
@Entity
@Table(name="model_superpathway"
    ,catalog="test_hibernate"
)
public class ModelSuperpathway  implements java.io.Serializable {


     private ModelSuperpathwayId id;

    public ModelSuperpathway() {
    }

    public ModelSuperpathway(ModelSuperpathwayId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pathwayIdpathway", column=@Column(name="pathway_idpathway", nullable=false) ), 
        @AttributeOverride(name="superpathway", column=@Column(name="superpathway", nullable=false) ) } )
    public ModelSuperpathwayId getId() {
        return this.id;
    }
    
    public void setId(ModelSuperpathwayId id) {
        this.id = id;
    }




}


