package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelSubunitId generated by hbm2java
 */
@Embeddable
public class ModelSubunitId implements java.io.Serializable {

	private int geneIdgene;
	private int enzymeProteinIdprotein;
	private String enzymeEcnumber;

	public ModelSubunitId() {
	}

	public ModelSubunitId(int geneIdgene, int enzymeProteinIdprotein, String enzymeEcnumber) {
		this.geneIdgene = geneIdgene;
		this.enzymeProteinIdprotein = enzymeProteinIdprotein;
		this.enzymeEcnumber = enzymeEcnumber;
	}

	@Column(name = "gene_idgene", nullable = false)
	public int getGeneIdgene() {
		return this.geneIdgene;
	}

	public void setGeneIdgene(int geneIdgene) {
		this.geneIdgene = geneIdgene;
	}

	@Column(name = "enzyme_protein_idprotein", nullable = false)
	public int getEnzymeProteinIdprotein() {
		return this.enzymeProteinIdprotein;
	}

	public void setEnzymeProteinIdprotein(int enzymeProteinIdprotein) {
		this.enzymeProteinIdprotein = enzymeProteinIdprotein;
	}

	@Column(name = "enzyme_ecnumber", nullable = false, length = 15)
	public String getEnzymeEcnumber() {
		return this.enzymeEcnumber;
	}

	public void setEnzymeEcnumber(String enzymeEcnumber) {
		this.enzymeEcnumber = enzymeEcnumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelSubunitId))
			return false;
		ModelSubunitId castOther = (ModelSubunitId) other;

		return (this.getGeneIdgene() == castOther.getGeneIdgene())
				&& (this.getEnzymeProteinIdprotein() == castOther.getEnzymeProteinIdprotein())
				&& ((this.getEnzymeEcnumber() == castOther.getEnzymeEcnumber())
						|| (this.getEnzymeEcnumber() != null && castOther.getEnzymeEcnumber() != null
								&& this.getEnzymeEcnumber().equals(castOther.getEnzymeEcnumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGeneIdgene();
		result = 37 * result + this.getEnzymeProteinIdprotein();
		result = 37 * result + (getEnzymeEcnumber() == null ? 0 : this.getEnzymeEcnumber().hashCode());
		return result;
	}

}
