package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelEnzymeHasModuleId generated by hbm2java
 */
@Embeddable
public class ModelEnzymeHasModuleId  implements java.io.Serializable {


     private String enzymeEcnumber;
     private int enzymeProteinIdprotein;
     private int moduleId;

    public ModelEnzymeHasModuleId() {
    }

    public ModelEnzymeHasModuleId(String enzymeEcnumber, int enzymeProteinIdprotein, int moduleId) {
       this.enzymeEcnumber = enzymeEcnumber;
       this.enzymeProteinIdprotein = enzymeProteinIdprotein;
       this.moduleId = moduleId;
    }
   


    @Column(name="enzyme_ecnumber", nullable=false, length=15)
    public String getEnzymeEcnumber() {
        return this.enzymeEcnumber;
    }
    
    public void setEnzymeEcnumber(String enzymeEcnumber) {
        this.enzymeEcnumber = enzymeEcnumber;
    }


    @Column(name="enzyme_protein_idprotein", nullable=false)
    public int getEnzymeProteinIdprotein() {
        return this.enzymeProteinIdprotein;
    }
    
    public void setEnzymeProteinIdprotein(int enzymeProteinIdprotein) {
        this.enzymeProteinIdprotein = enzymeProteinIdprotein;
    }


    @Column(name="module_id", nullable=false)
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelEnzymeHasModuleId) ) return false;
		 ModelEnzymeHasModuleId castOther = ( ModelEnzymeHasModuleId ) other; 
         
		 return ( (this.getEnzymeEcnumber()==castOther.getEnzymeEcnumber()) || ( this.getEnzymeEcnumber()!=null && castOther.getEnzymeEcnumber()!=null && this.getEnzymeEcnumber().equals(castOther.getEnzymeEcnumber()) ) )
 && (this.getEnzymeProteinIdprotein()==castOther.getEnzymeProteinIdprotein())
 && (this.getModuleId()==castOther.getModuleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEnzymeEcnumber() == null ? 0 : this.getEnzymeEcnumber().hashCode() );
         result = 37 * result + this.getEnzymeProteinIdprotein();
         result = 37 * result + this.getModuleId();
         return result;
   }   


}


