package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelPathwayHasReactionId generated by hbm2java
 */
@Embeddable
public class ModelPathwayHasReactionId  implements java.io.Serializable {


     private int reactionIdreaction;
     private int pathwayIdpathway;

    public ModelPathwayHasReactionId() {
    }

    public ModelPathwayHasReactionId(int reactionIdreaction, int pathwayIdpathway) {
       this.reactionIdreaction = reactionIdreaction;
       this.pathwayIdpathway = pathwayIdpathway;
    }
   


    @Column(name="reaction_idreaction", nullable=false)
    public int getReactionIdreaction() {
        return this.reactionIdreaction;
    }
    
    public void setReactionIdreaction(int reactionIdreaction) {
        this.reactionIdreaction = reactionIdreaction;
    }


    @Column(name="pathway_idpathway", nullable=false)
    public int getPathwayIdpathway() {
        return this.pathwayIdpathway;
    }
    
    public void setPathwayIdpathway(int pathwayIdpathway) {
        this.pathwayIdpathway = pathwayIdpathway;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelPathwayHasReactionId) ) return false;
		 ModelPathwayHasReactionId castOther = ( ModelPathwayHasReactionId ) other; 
         
		 return (this.getReactionIdreaction()==castOther.getReactionIdreaction())
 && (this.getPathwayIdpathway()==castOther.getPathwayIdpathway());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getReactionIdreaction();
         result = 37 * result + this.getPathwayIdpathway();
         return result;
   }   


}


