package hibernate.merlin_hibernate.entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelEffector generated by hbm2java
 */
@Entity
@Table(name = "model_effector", catalog = "sysbio_model")
public class ModelEffector implements java.io.Serializable {

	private ModelEffectorId id;

	public ModelEffector() {
	}

	public ModelEffector(ModelEffectorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "proteinIdprotein", column = @Column(name = "protein_idprotein", nullable = false)),
			@AttributeOverride(name = "compoundIdcompound", column = @Column(name = "compound_idcompound", nullable = false)) })
	public ModelEffectorId getId() {
		return this.id;
	}

	public void setId(ModelEffectorId id) {
		this.id = id;
	}

}
