package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModelExperimentDescription generated by hbm2java
 */
@Entity
@Table(name = "model_experiment_description", catalog = "sysbio_model")
public class ModelExperimentDescription implements java.io.Serializable {

	private ModelExperimentDescriptionId id;
	private ModelExperimentalFactor modelExperimentalFactor;
	private String value;

	public ModelExperimentDescription() {
	}

	public ModelExperimentDescription(ModelExperimentDescriptionId id, ModelExperimentalFactor modelExperimentalFactor,
			String value) {
		this.id = id;
		this.modelExperimentalFactor = modelExperimentalFactor;
		this.value = value;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idexperiment", column = @Column(name = "idexperiment", nullable = false)),
			@AttributeOverride(name = "experimentDescriptionalFactorIdexperimentalFactor", column = @Column(name = "experiment_descriptional_factor_idexperimental_factor", nullable = false)) })
	public ModelExperimentDescriptionId getId() {
		return this.id;
	}

	public void setId(ModelExperimentDescriptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "experiment_descriptional_factor_idexperimental_factor", nullable = false, insertable = false, updatable = false)
	public ModelExperimentalFactor getModelExperimentalFactor() {
		return this.modelExperimentalFactor;
	}

	public void setModelExperimentalFactor(ModelExperimentalFactor modelExperimentalFactor) {
		this.modelExperimentalFactor = modelExperimentalFactor;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
