package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelEnzymeId generated by hbm2java
 */
@Embeddable
public class ModelEnzymeId  implements java.io.Serializable {


     private String ecnumber;
     private int proteinIdprotein;

    public ModelEnzymeId() {
    }

    public ModelEnzymeId(String ecnumber, int proteinIdprotein) {
       this.ecnumber = ecnumber;
       this.proteinIdprotein = proteinIdprotein;
    }
   


    @Column(name="ecnumber", nullable=false, length=15)
    public String getEcnumber() {
        return this.ecnumber;
    }
    
    public void setEcnumber(String ecnumber) {
        this.ecnumber = ecnumber;
    }


    @Column(name="protein_idprotein", nullable=false)
    public int getProteinIdprotein() {
        return this.proteinIdprotein;
    }
    
    public void setProteinIdprotein(int proteinIdprotein) {
        this.proteinIdprotein = proteinIdprotein;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelEnzymeId) ) return false;
		 ModelEnzymeId castOther = ( ModelEnzymeId ) other; 
         
		 return ( (this.getEcnumber()==castOther.getEcnumber()) || ( this.getEcnumber()!=null && castOther.getEcnumber()!=null && this.getEcnumber().equals(castOther.getEcnumber()) ) )
 && (this.getProteinIdprotein()==castOther.getProteinIdprotein());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEcnumber() == null ? 0 : this.getEcnumber().hashCode() );
         result = 37 * result + this.getProteinIdprotein();
         return result;
   }   


}


