package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelEnzyme generated by hbm2java
 */
@Entity
@Table(name="model_enzyme"
    ,catalog="test_hibernate"
)
public class ModelEnzyme  implements java.io.Serializable {


     private ModelEnzymeId id;
     private Float optimalPh;
     private String posttranslationalModification;
     private Boolean inModel;
     private String source;
     private String gprStatus;
     private Set<ModelEnzymeHasModule> modelEnzymeHasModules = new HashSet<ModelEnzymeHasModule>(0);

    public ModelEnzyme() {
    }

	
    public ModelEnzyme(ModelEnzymeId id) {
        this.id = id;
    }
    public ModelEnzyme(ModelEnzymeId id, Float optimalPh, String posttranslationalModification, Boolean inModel, String source, String gprStatus, Set<ModelEnzymeHasModule> modelEnzymeHasModules) {
       this.id = id;
       this.optimalPh = optimalPh;
       this.posttranslationalModification = posttranslationalModification;
       this.inModel = inModel;
       this.source = source;
       this.gprStatus = gprStatus;
       this.modelEnzymeHasModules = modelEnzymeHasModules;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ecnumber", column=@Column(name="ecnumber", nullable=false, length=15) ), 
        @AttributeOverride(name="proteinIdprotein", column=@Column(name="protein_idprotein", nullable=false) ) } )
    public ModelEnzymeId getId() {
        return this.id;
    }
    
    public void setId(ModelEnzymeId id) {
        this.id = id;
    }

    
    @Column(name="optimal_ph", precision=12, scale=0)
    public Float getOptimalPh() {
        return this.optimalPh;
    }
    
    public void setOptimalPh(Float optimalPh) {
        this.optimalPh = optimalPh;
    }

    
    @Column(name="posttranslational_modification", length=100)
    public String getPosttranslationalModification() {
        return this.posttranslationalModification;
    }
    
    public void setPosttranslationalModification(String posttranslationalModification) {
        this.posttranslationalModification = posttranslationalModification;
    }

    
    @Column(name="inModel")
    public Boolean getInModel() {
        return this.inModel;
    }
    
    public void setInModel(Boolean inModel) {
        this.inModel = inModel;
    }

    
    @Column(name="source", length=45)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="gpr_status", length=45)
    public String getGprStatus() {
        return this.gprStatus;
    }
    
    public void setGprStatus(String gprStatus) {
        this.gprStatus = gprStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="modelEnzyme")
    public Set<ModelEnzymeHasModule> getModelEnzymeHasModules() {
        return this.modelEnzymeHasModules;
    }
    
    public void setModelEnzymeHasModules(Set<ModelEnzymeHasModule> modelEnzymeHasModules) {
        this.modelEnzymeHasModules = modelEnzymeHasModules;
    }




}


