package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelRegulatoryEvent generated by hbm2java
 */
@Entity
@Table(name="model_regulatory_event"
    ,catalog="test_hibernate"
)
public class ModelRegulatoryEvent  implements java.io.Serializable {


     private ModelRegulatoryEventId id;
     private BigDecimal bindingSitePosition;

    public ModelRegulatoryEvent() {
    }

	
    public ModelRegulatoryEvent(ModelRegulatoryEventId id) {
        this.id = id;
    }
    public ModelRegulatoryEvent(ModelRegulatoryEventId id, BigDecimal bindingSitePosition) {
       this.id = id;
       this.bindingSitePosition = bindingSitePosition;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="proteinIdprotein", column=@Column(name="protein_idprotein", nullable=false) ), 
        @AttributeOverride(name="promoterIdpromoter", column=@Column(name="promoter_idpromoter", nullable=false) ), 
        @AttributeOverride(name="riFunctionIdriFunction", column=@Column(name="ri_function_idri_function", nullable=false) ) } )
    public ModelRegulatoryEventId getId() {
        return this.id;
    }
    
    public void setId(ModelRegulatoryEventId id) {
        this.id = id;
    }

    
    @Column(name="binding_site_position", precision=15, scale=6)
    public BigDecimal getBindingSitePosition() {
        return this.bindingSitePosition;
    }
    
    public void setBindingSitePosition(BigDecimal bindingSitePosition) {
        this.bindingSitePosition = bindingSitePosition;
    }




}


