package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelRiFunction generated by hbm2java
 */
@Entity
@Table(name="model_ri_function"
    ,catalog="test_hibernate"
)
public class ModelRiFunction  implements java.io.Serializable {


     private Integer idriFunction;
     private String symbol;
     private String riFunction;

    public ModelRiFunction() {
    }

    public ModelRiFunction(String symbol, String riFunction) {
       this.symbol = symbol;
       this.riFunction = riFunction;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idri_function", unique=true, nullable=false)
    public Integer getIdriFunction() {
        return this.idriFunction;
    }
    
    public void setIdriFunction(Integer idriFunction) {
        this.idriFunction = idriFunction;
    }

    
    @Column(name="symbol", length=2)
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    
    @Column(name="ri_function", length=20)
    public String getRiFunction() {
        return this.riFunction;
    }
    
    public void setRiFunction(String riFunction) {
        this.riFunction = riFunction;
    }




}


