package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelSameAsId generated by hbm2java
 */
@Embeddable
public class ModelSameAsId  implements java.io.Serializable {


     private int metaboliteId;
     private int similarMetaboliteId;

    public ModelSameAsId() {
    }

    public ModelSameAsId(int metaboliteId, int similarMetaboliteId) {
       this.metaboliteId = metaboliteId;
       this.similarMetaboliteId = similarMetaboliteId;
    }
   


    @Column(name="metabolite_id", nullable=false)
    public int getMetaboliteId() {
        return this.metaboliteId;
    }
    
    public void setMetaboliteId(int metaboliteId) {
        this.metaboliteId = metaboliteId;
    }


    @Column(name="similar_metabolite_id", nullable=false)
    public int getSimilarMetaboliteId() {
        return this.similarMetaboliteId;
    }
    
    public void setSimilarMetaboliteId(int similarMetaboliteId) {
        this.similarMetaboliteId = similarMetaboliteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelSameAsId) ) return false;
		 ModelSameAsId castOther = ( ModelSameAsId ) other; 
         
		 return (this.getMetaboliteId()==castOther.getMetaboliteId())
 && (this.getSimilarMetaboliteId()==castOther.getSimilarMetaboliteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMetaboliteId();
         result = 37 * result + this.getSimilarMetaboliteId();
         return result;
   }   


}


