package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelSequence generated by hbm2java
 */
@Entity
@Table(name = "model_sequence", catalog = "sysbio_model")
public class ModelSequence implements java.io.Serializable {

	private Integer idsequence;
	private ModelGene modelGene;
	private String sequenceType;
	private String sequence;
	private Integer sequenceLength;
	private Set<ModelSequenceFeature> modelSequenceFeatures = new HashSet<ModelSequenceFeature>(0);

	public ModelSequence() {
	}

	public ModelSequence(ModelGene modelGene) {
		this.modelGene = modelGene;
	}

	public ModelSequence(ModelGene modelGene, String sequenceType, String sequence, Integer sequenceLength,
			Set<ModelSequenceFeature> modelSequenceFeatures) {
		this.modelGene = modelGene;
		this.sequenceType = sequenceType;
		this.sequence = sequence;
		this.sequenceLength = sequenceLength;
		this.modelSequenceFeatures = modelSequenceFeatures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsequence", unique = true, nullable = false)
	public Integer getIdsequence() {
		return this.idsequence;
	}

	public void setIdsequence(Integer idsequence) {
		this.idsequence = idsequence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gene_idgene", nullable = false)
	public ModelGene getModelGene() {
		return this.modelGene;
	}

	public void setModelGene(ModelGene modelGene) {
		this.modelGene = modelGene;
	}

	@Column(name = "sequence_type", length = 20)
	public String getSequenceType() {
		return this.sequenceType;
	}

	public void setSequenceType(String sequenceType) {
		this.sequenceType = sequenceType;
	}

	@Column(name = "sequence", length = 65535)
	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	@Column(name = "sequence_length")
	public Integer getSequenceLength() {
		return this.sequenceLength;
	}

	public void setSequenceLength(Integer sequenceLength) {
		this.sequenceLength = sequenceLength;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelSequence")
	public Set<ModelSequenceFeature> getModelSequenceFeatures() {
		return this.modelSequenceFeatures;
	}

	public void setModelSequenceFeatures(Set<ModelSequenceFeature> modelSequenceFeatures) {
		this.modelSequenceFeatures = modelSequenceFeatures;
	}

}
