package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ModelSequenceFeature generated by hbm2java
 */
@Entity
@Table(name = "model_sequence_feature", catalog = "test_hibernate")
public class ModelSequenceFeature implements java.io.Serializable {

	private int featureIdfeature;
	private ModelFeature modelFeature;
	private ModelSequence modelSequence;
	private String startPositionApproximate;
	private String endPositionApproximate;

	public ModelSequenceFeature() {
	}

	public ModelSequenceFeature(ModelFeature modelFeature, ModelSequence modelSequence) {
		this.modelFeature = modelFeature;
		this.modelSequence = modelSequence;
	}

	public ModelSequenceFeature(ModelFeature modelFeature, ModelSequence modelSequence, String startPositionApproximate,
			String endPositionApproximate) {
		this.modelFeature = modelFeature;
		this.modelSequence = modelSequence;
		this.startPositionApproximate = startPositionApproximate;
		this.endPositionApproximate = endPositionApproximate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "modelFeature"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "feature_idfeature", unique = true, nullable = false)
	public int getFeatureIdfeature() {
		return this.featureIdfeature;
	}

	public void setFeatureIdfeature(int featureIdfeature) {
		this.featureIdfeature = featureIdfeature;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ModelFeature getModelFeature() {
		return this.modelFeature;
	}

	public void setModelFeature(ModelFeature modelFeature) {
		this.modelFeature = modelFeature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sequence_idsequence", nullable = false)
	public ModelSequence getModelSequence() {
		return this.modelSequence;
	}

	public void setModelSequence(ModelSequence modelSequence) {
		this.modelSequence = modelSequence;
	}

	@Column(name = "start_position_approximate", length = 20)
	public String getStartPositionApproximate() {
		return this.startPositionApproximate;
	}

	public void setStartPositionApproximate(String startPositionApproximate) {
		this.startPositionApproximate = startPositionApproximate;
	}

	@Column(name = "end_position_approximate", length = 20)
	public String getEndPositionApproximate() {
		return this.endPositionApproximate;
	}

	public void setEndPositionApproximate(String endPositionApproximate) {
		this.endPositionApproximate = endPositionApproximate;
	}

}
