package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelExperimentalFactor generated by hbm2java
 */
@Entity
@Table(name="model_experimental_factor"
    ,catalog="test_hibernate"
)
public class ModelExperimentalFactor  implements java.io.Serializable {


     private int idexperimentalFactor;
     private String factor;

    public ModelExperimentalFactor() {
    }

	
    public ModelExperimentalFactor(int idexperimentalFactor) {
        this.idexperimentalFactor = idexperimentalFactor;
    }
    public ModelExperimentalFactor(int idexperimentalFactor, String factor) {
       this.idexperimentalFactor = idexperimentalFactor;
       this.factor = factor;
    }
   
     @Id 

    
    @Column(name="idexperimental_factor", unique=true, nullable=false)
    public int getIdexperimentalFactor() {
        return this.idexperimentalFactor;
    }
    
    public void setIdexperimentalFactor(int idexperimentalFactor) {
        this.idexperimentalFactor = idexperimentalFactor;
    }

    
    @Column(name="factor")
    public String getFactor() {
        return this.factor;
    }
    
    public void setFactor(String factor) {
        this.factor = factor;
    }




}


