package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelModuleHasOrthologyId generated by hbm2java
 */
@Embeddable
public class ModelModuleHasOrthologyId  implements java.io.Serializable {


     private int moduleId;
     private int orthologyId;

    public ModelModuleHasOrthologyId() {
    }

    public ModelModuleHasOrthologyId(int moduleId, int orthologyId) {
       this.moduleId = moduleId;
       this.orthologyId = orthologyId;
    }
   


    @Column(name="module_id", nullable=false)
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }


    @Column(name="orthology_id", nullable=false)
    public int getOrthologyId() {
        return this.orthologyId;
    }
    
    public void setOrthologyId(int orthologyId) {
        this.orthologyId = orthologyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelModuleHasOrthologyId) ) return false;
		 ModelModuleHasOrthologyId castOther = ( ModelModuleHasOrthologyId ) other; 
         
		 return (this.getModuleId()==castOther.getModuleId())
 && (this.getOrthologyId()==castOther.getOrthologyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getModuleId();
         result = 37 * result + this.getOrthologyId();
         return result;
   }   


}


