package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelGene generated by hbm2java
 */
@Entity
@Table(name="model_gene"
    ,catalog="test_hibernate"
)
public class ModelGene  implements java.io.Serializable {


     private Integer idgene;
     private Integer chromosomeIdchromosome;
     private String name;
     private String locusTag;
     private String transcriptionDirection;
     private String leftEndPosition;
     private String rightEndPosition;
     private String booleanRule;
     private String origin;
     private String sequenceId;

    public ModelGene() {
    }

	
    public ModelGene(String origin, String sequenceId) {
        this.origin = origin;
        this.sequenceId = sequenceId;
    }
    public ModelGene(Integer chromosomeIdchromosome, String name, String locusTag, String transcriptionDirection, String leftEndPosition, String rightEndPosition, String booleanRule, String origin, String sequenceId) {
       this.chromosomeIdchromosome = chromosomeIdchromosome;
       this.name = name;
       this.locusTag = locusTag;
       this.transcriptionDirection = transcriptionDirection;
       this.leftEndPosition = leftEndPosition;
       this.rightEndPosition = rightEndPosition;
       this.booleanRule = booleanRule;
       this.origin = origin;
       this.sequenceId = sequenceId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idgene", unique=true, nullable=false)
    public Integer getIdgene() {
        return this.idgene;
    }
    
    public void setIdgene(Integer idgene) {
        this.idgene = idgene;
    }

    
    @Column(name="chromosome_idchromosome")
    public Integer getChromosomeIdchromosome() {
        return this.chromosomeIdchromosome;
    }
    
    public void setChromosomeIdchromosome(Integer chromosomeIdchromosome) {
        this.chromosomeIdchromosome = chromosomeIdchromosome;
    }

    
    @Column(name="name", length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="locusTag", length=45)
    public String getLocusTag() {
        return this.locusTag;
    }
    
    public void setLocusTag(String locusTag) {
        this.locusTag = locusTag;
    }

    
    @Column(name="transcription_direction", length=3)
    public String getTranscriptionDirection() {
        return this.transcriptionDirection;
    }
    
    public void setTranscriptionDirection(String transcriptionDirection) {
        this.transcriptionDirection = transcriptionDirection;
    }

    
    @Column(name="left_end_position", length=45)
    public String getLeftEndPosition() {
        return this.leftEndPosition;
    }
    
    public void setLeftEndPosition(String leftEndPosition) {
        this.leftEndPosition = leftEndPosition;
    }

    
    @Column(name="right_end_position", length=100)
    public String getRightEndPosition() {
        return this.rightEndPosition;
    }
    
    public void setRightEndPosition(String rightEndPosition) {
        this.rightEndPosition = rightEndPosition;
    }

    
    @Column(name="boolean_rule", length=200)
    public String getBooleanRule() {
        return this.booleanRule;
    }
    
    public void setBooleanRule(String booleanRule) {
        this.booleanRule = booleanRule;
    }

    
    @Column(name="origin", nullable=false, length=40)
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    
    @Column(name="sequence_id", nullable=false, length=45)
    public String getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId;
    }




}


