package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelStoichiometryId generated by hbm2java
 */
@Embeddable
public class ModelStoichiometryId implements java.io.Serializable {

	private int idstoichiometry;
	private int reactionIdreaction;
	private int compoundIdcompound;
	private int compartmentIdcompartment;

	public ModelStoichiometryId() {
	}

	public ModelStoichiometryId(int idstoichiometry, int reactionIdreaction, int compoundIdcompound,
			int compartmentIdcompartment) {
		this.idstoichiometry = idstoichiometry;
		this.reactionIdreaction = reactionIdreaction;
		this.compoundIdcompound = compoundIdcompound;
		this.compartmentIdcompartment = compartmentIdcompartment;
	}

	@Column(name = "idstoichiometry", nullable = false)
	public int getIdstoichiometry() {
		return this.idstoichiometry;
	}

	public void setIdstoichiometry(int idstoichiometry) {
		this.idstoichiometry = idstoichiometry;
	}

	@Column(name = "reaction_idreaction", nullable = false)
	public int getReactionIdreaction() {
		return this.reactionIdreaction;
	}

	public void setReactionIdreaction(int reactionIdreaction) {
		this.reactionIdreaction = reactionIdreaction;
	}

	@Column(name = "compound_idcompound", nullable = false)
	public int getCompoundIdcompound() {
		return this.compoundIdcompound;
	}

	public void setCompoundIdcompound(int compoundIdcompound) {
		this.compoundIdcompound = compoundIdcompound;
	}

	@Column(name = "compartment_idcompartment", nullable = false)
	public int getCompartmentIdcompartment() {
		return this.compartmentIdcompartment;
	}

	public void setCompartmentIdcompartment(int compartmentIdcompartment) {
		this.compartmentIdcompartment = compartmentIdcompartment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelStoichiometryId))
			return false;
		ModelStoichiometryId castOther = (ModelStoichiometryId) other;

		return (this.getIdstoichiometry() == castOther.getIdstoichiometry())
				&& (this.getReactionIdreaction() == castOther.getReactionIdreaction())
				&& (this.getCompoundIdcompound() == castOther.getCompoundIdcompound())
				&& (this.getCompartmentIdcompartment() == castOther.getCompartmentIdcompartment());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdstoichiometry();
		result = 37 * result + this.getReactionIdreaction();
		result = 37 * result + this.getCompoundIdcompound();
		result = 37 * result + this.getCompartmentIdcompartment();
		return result;
	}

}
