package hibernate.merlin_hibernate.entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelIsSuperReactionId generated by hbm2java
 */
@Embeddable
public class ModelIsSuperReactionId implements java.io.Serializable {

	private int superReactionId;
	private int subReactionId;

	public ModelIsSuperReactionId() {
	}

	public ModelIsSuperReactionId(int superReactionId, int subReactionId) {
		this.superReactionId = superReactionId;
		this.subReactionId = subReactionId;
	}

	@Column(name = "super_reaction_id", nullable = false)
	public int getSuperReactionId() {
		return this.superReactionId;
	}

	public void setSuperReactionId(int superReactionId) {
		this.superReactionId = superReactionId;
	}

	@Column(name = "sub_reaction_id", nullable = false)
	public int getSubReactionId() {
		return this.subReactionId;
	}

	public void setSubReactionId(int subReactionId) {
		this.subReactionId = subReactionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelIsSuperReactionId))
			return false;
		ModelIsSuperReactionId castOther = (ModelIsSuperReactionId) other;

		return (this.getSuperReactionId() == castOther.getSuperReactionId())
				&& (this.getSubReactionId() == castOther.getSubReactionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSuperReactionId();
		result = 37 * result + this.getSubReactionId();
		return result;
	}

}
