package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelPathwayHasModule generated by hbm2java
 */
@Entity
@Table(name="model_pathway_has_module"
    ,catalog="test_hibernate"
)
public class ModelPathwayHasModule  implements java.io.Serializable {


     private ModelPathwayHasModuleId id;

    public ModelPathwayHasModule() {
    }

    public ModelPathwayHasModule(ModelPathwayHasModuleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pathwayIdpathway", column=@Column(name="pathway_idpathway", nullable=false) ), 
        @AttributeOverride(name="moduleId", column=@Column(name="module_id", nullable=false) ) } )
    public ModelPathwayHasModuleId getId() {
        return this.id;
    }
    
    public void setId(ModelPathwayHasModuleId id) {
        this.id = id;
    }




}


