package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelPathwayHasReaction generated by hbm2java
 */
@Entity
@Table(name="model_pathway_has_reaction"
    ,catalog="test_hibernate"
)
public class ModelPathwayHasReaction  implements java.io.Serializable {


     private ModelPathwayHasReactionId id;

    public ModelPathwayHasReaction() {
    }

    public ModelPathwayHasReaction(ModelPathwayHasReactionId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="reactionIdreaction", column=@Column(name="reaction_idreaction", nullable=false) ), 
        @AttributeOverride(name="pathwayIdpathway", column=@Column(name="pathway_idpathway", nullable=false) ) } )
    public ModelPathwayHasReactionId getId() {
        return this.id;
    }
    
    public void setId(ModelPathwayHasReactionId id) {
        this.id = id;
    }




}


