package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelModulesHasCompoundId generated by hbm2java
 */
@Embeddable
public class ModelModulesHasCompoundId  implements java.io.Serializable {


     private int modulesId;
     private int compoundIdcompound;

    public ModelModulesHasCompoundId() {
    }

    public ModelModulesHasCompoundId(int modulesId, int compoundIdcompound) {
       this.modulesId = modulesId;
       this.compoundIdcompound = compoundIdcompound;
    }
   


    @Column(name="modules_id", nullable=false)
    public int getModulesId() {
        return this.modulesId;
    }
    
    public void setModulesId(int modulesId) {
        this.modulesId = modulesId;
    }


    @Column(name="compound_idcompound", nullable=false)
    public int getCompoundIdcompound() {
        return this.compoundIdcompound;
    }
    
    public void setCompoundIdcompound(int compoundIdcompound) {
        this.compoundIdcompound = compoundIdcompound;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelModulesHasCompoundId) ) return false;
		 ModelModulesHasCompoundId castOther = ( ModelModulesHasCompoundId ) other; 
         
		 return (this.getModulesId()==castOther.getModulesId())
 && (this.getCompoundIdcompound()==castOther.getCompoundIdcompound());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getModulesId();
         result = 37 * result + this.getCompoundIdcompound();
         return result;
   }   


}


