package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelProtein generated by hbm2java
 */
@Entity
@Table(name="model_protein"
    ,catalog="test_hibernate"
)
public class ModelProtein  implements java.io.Serializable {


     private Integer idprotein;
     private String name;
     private String class_;
     private String inchi;
     private Float molecularWeight;
     private Float molecularWeightExp;
     private Float molecularWeightKd;
     private Float molecularWeightSeq;
     private Float pi;

    public ModelProtein() {
    }

	
    public ModelProtein(String name) {
        this.name = name;
    }
    public ModelProtein(String name, String class_, String inchi, Float molecularWeight, Float molecularWeightExp, Float molecularWeightKd, Float molecularWeightSeq, Float pi) {
       this.name = name;
       this.class_ = class_;
       this.inchi = inchi;
       this.molecularWeight = molecularWeight;
       this.molecularWeightExp = molecularWeightExp;
       this.molecularWeightKd = molecularWeightKd;
       this.molecularWeightSeq = molecularWeightSeq;
       this.pi = pi;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprotein", unique=true, nullable=false)
    public Integer getIdprotein() {
        return this.idprotein;
    }
    
    public void setIdprotein(Integer idprotein) {
        this.idprotein = idprotein;
    }

    
    @Column(name="name", nullable=false, length=400)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="class", length=120)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="inchi")
    public String getInchi() {
        return this.inchi;
    }
    
    public void setInchi(String inchi) {
        this.inchi = inchi;
    }

    
    @Column(name="molecular_weight", precision=12, scale=0)
    public Float getMolecularWeight() {
        return this.molecularWeight;
    }
    
    public void setMolecularWeight(Float molecularWeight) {
        this.molecularWeight = molecularWeight;
    }

    
    @Column(name="molecular_weight_exp", precision=12, scale=0)
    public Float getMolecularWeightExp() {
        return this.molecularWeightExp;
    }
    
    public void setMolecularWeightExp(Float molecularWeightExp) {
        this.molecularWeightExp = molecularWeightExp;
    }

    
    @Column(name="molecular_weight_kd", precision=12, scale=0)
    public Float getMolecularWeightKd() {
        return this.molecularWeightKd;
    }
    
    public void setMolecularWeightKd(Float molecularWeightKd) {
        this.molecularWeightKd = molecularWeightKd;
    }

    
    @Column(name="molecular_weight_seq", precision=12, scale=0)
    public Float getMolecularWeightSeq() {
        return this.molecularWeightSeq;
    }
    
    public void setMolecularWeightSeq(Float molecularWeightSeq) {
        this.molecularWeightSeq = molecularWeightSeq;
    }

    
    @Column(name="pi", precision=12, scale=0)
    public Float getPi() {
        return this.pi;
    }
    
    public void setPi(Float pi) {
        this.pi = pi;
    }




}


