package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModelProteinComposition generated by hbm2java
 */
@Entity
@Table(name = "model_protein_composition", catalog = "sysbio_model")
public class ModelProteinComposition implements java.io.Serializable {

	private ModelProteinCompositionId id;
	private ModelProtein modelProtein;

	public ModelProteinComposition() {
	}

	public ModelProteinComposition(ModelProteinCompositionId id, ModelProtein modelProtein) {
		this.id = id;
		this.modelProtein = modelProtein;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "proteinIdprotein", column = @Column(name = "protein_idprotein", nullable = false)),
			@AttributeOverride(name = "subunit", column = @Column(name = "subunit", nullable = false)) })
	public ModelProteinCompositionId getId() {
		return this.id;
	}

	public void setId(ModelProteinCompositionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "protein_idprotein", nullable = false, insertable = false, updatable = false)
	public ModelProtein getModelProtein() {
		return this.modelProtein;
	}

	public void setModelProtein(ModelProtein modelProtein) {
		this.modelProtein = modelProtein;
	}

}
