package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelExperimentSubstrateAffinity generated by hbm2java
 */
@Entity
@Table(name="model_experiment_substrate_affinity"
    ,catalog="test_hibernate"
)
public class ModelExperimentSubstrateAffinity  implements java.io.Serializable {


     private ModelExperimentSubstrateAffinityId id;
     private Float substrateAffinity;

    public ModelExperimentSubstrateAffinity() {
    }

	
    public ModelExperimentSubstrateAffinity(ModelExperimentSubstrateAffinityId id) {
        this.id = id;
    }
    public ModelExperimentSubstrateAffinity(ModelExperimentSubstrateAffinityId id, Float substrateAffinity) {
       this.id = id;
       this.substrateAffinity = substrateAffinity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="experimentDescription", column=@Column(name="experiment_description", nullable=false) ), 
        @AttributeOverride(name="compoundIdcompound", column=@Column(name="compound_idcompound", nullable=false) ), 
        @AttributeOverride(name="proteinIdprotein", column=@Column(name="protein_idprotein", nullable=false) ) } )
    public ModelExperimentSubstrateAffinityId getId() {
        return this.id;
    }
    
    public void setId(ModelExperimentSubstrateAffinityId id) {
        this.id = id;
    }

    
    @Column(name="substrate_affinity", precision=12, scale=0)
    public Float getSubstrateAffinity() {
        return this.substrateAffinity;
    }
    
    public void setSubstrateAffinity(Float substrateAffinity) {
        this.substrateAffinity = substrateAffinity;
    }




}


