package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelEffectorId generated by hbm2java
 */
@Embeddable
public class ModelEffectorId  implements java.io.Serializable {


     private int proteinIdprotein;
     private int compoundIdcompound;

    public ModelEffectorId() {
    }

    public ModelEffectorId(int proteinIdprotein, int compoundIdcompound) {
       this.proteinIdprotein = proteinIdprotein;
       this.compoundIdcompound = compoundIdcompound;
    }
   


    @Column(name="protein_idprotein", nullable=false)
    public int getProteinIdprotein() {
        return this.proteinIdprotein;
    }
    
    public void setProteinIdprotein(int proteinIdprotein) {
        this.proteinIdprotein = proteinIdprotein;
    }


    @Column(name="compound_idcompound", nullable=false)
    public int getCompoundIdcompound() {
        return this.compoundIdcompound;
    }
    
    public void setCompoundIdcompound(int compoundIdcompound) {
        this.compoundIdcompound = compoundIdcompound;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelEffectorId) ) return false;
		 ModelEffectorId castOther = ( ModelEffectorId ) other; 
         
		 return (this.getProteinIdprotein()==castOther.getProteinIdprotein())
 && (this.getCompoundIdcompound()==castOther.getCompoundIdcompound());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProteinIdprotein();
         result = 37 * result + this.getCompoundIdcompound();
         return result;
   }   


}


