package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelGeneHasCompartment generated by hbm2java
 */
@Entity
@Table(name="model_gene_has_compartment"
    ,catalog="test_hibernate"
)
public class ModelGeneHasCompartment  implements java.io.Serializable {


     private ModelGeneHasCompartmentId id;
     private Boolean primaryLocation;
     private String score;

    public ModelGeneHasCompartment() {
    }

	
    public ModelGeneHasCompartment(ModelGeneHasCompartmentId id) {
        this.id = id;
    }
    public ModelGeneHasCompartment(ModelGeneHasCompartmentId id, Boolean primaryLocation, String score) {
       this.id = id;
       this.primaryLocation = primaryLocation;
       this.score = score;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="geneIdgene", column=@Column(name="gene_idgene", nullable=false) ), 
        @AttributeOverride(name="compartmentIdcompartment", column=@Column(name="compartment_idcompartment", nullable=false) ) } )
    public ModelGeneHasCompartmentId getId() {
        return this.id;
    }
    
    public void setId(ModelGeneHasCompartmentId id) {
        this.id = id;
    }

    
    @Column(name="primaryLocation")
    public Boolean getPrimaryLocation() {
        return this.primaryLocation;
    }
    
    public void setPrimaryLocation(Boolean primaryLocation) {
        this.primaryLocation = primaryLocation;
    }

    
    @Column(name="score", length=20)
    public String getScore() {
        return this.score;
    }
    
    public void setScore(String score) {
        this.score = score;
    }




}


