package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelChromosome generated by hbm2java
 */
@Entity
@Table(name = "model_chromosome", catalog = "sysbio_model")
public class ModelChromosome implements java.io.Serializable {

	private Integer idchromosome;
	private String name;
	private Set<ModelGene> modelGenes = new HashSet<ModelGene>(0);

	public ModelChromosome() {
	}

	public ModelChromosome(String name) {
		this.name = name;
	}

	public ModelChromosome(String name, Set<ModelGene> modelGenes) {
		this.name = name;
		this.modelGenes = modelGenes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idchromosome", unique = true, nullable = false)
	public Integer getIdchromosome() {
		return this.idchromosome;
	}

	public void setIdchromosome(Integer idchromosome) {
		this.idchromosome = idchromosome;
	}

	@Column(name = "name", nullable = false, length = 15)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelChromosome")
	public Set<ModelGene> getModelGenes() {
		return this.modelGenes;
	}

	public void setModelGenes(Set<ModelGene> modelGenes) {
		this.modelGenes = modelGenes;
	}

}
