package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelReaction generated by hbm2java
 */
@Entity
@Table(name="model_reaction"
    ,catalog="test_hibernate"
)
public class ModelReaction  implements java.io.Serializable {


     private Integer idreaction;
     private String name;
     private String equation;
     private Boolean reversible;
     private String booleanRule;
     private Boolean inModel;
     private Boolean isGeneric;
     private Boolean isSpontaneous;
     private Boolean isNonEnzymatic;
     private String source;
     private boolean originalReaction;
     private Integer compartmentIdcompartment;
     private String notes;
     private Float lowerBound;
     private Float upperBound;

    public ModelReaction() {
    }

	
    public ModelReaction(String source, boolean originalReaction) {
        this.source = source;
        this.originalReaction = originalReaction;
    }
    public ModelReaction(String name, String equation, Boolean reversible, String booleanRule, Boolean inModel, Boolean isGeneric, Boolean isSpontaneous, Boolean isNonEnzymatic, String source, boolean originalReaction, Integer compartmentIdcompartment, String notes, Float lowerBound, Float upperBound) {
       this.name = name;
       this.equation = equation;
       this.reversible = reversible;
       this.booleanRule = booleanRule;
       this.inModel = inModel;
       this.isGeneric = isGeneric;
       this.isSpontaneous = isSpontaneous;
       this.isNonEnzymatic = isNonEnzymatic;
       this.source = source;
       this.originalReaction = originalReaction;
       this.compartmentIdcompartment = compartmentIdcompartment;
       this.notes = notes;
       this.lowerBound = lowerBound;
       this.upperBound = upperBound;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idreaction", unique=true, nullable=false)
    public Integer getIdreaction() {
        return this.idreaction;
    }
    
    public void setIdreaction(Integer idreaction) {
        this.idreaction = idreaction;
    }

    
    @Column(name="name", length=400)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="equation", length=65535)
    public String getEquation() {
        return this.equation;
    }
    
    public void setEquation(String equation) {
        this.equation = equation;
    }

    
    @Column(name="reversible")
    public Boolean getReversible() {
        return this.reversible;
    }
    
    public void setReversible(Boolean reversible) {
        this.reversible = reversible;
    }

    
    @Column(name="boolean_rule", length=400)
    public String getBooleanRule() {
        return this.booleanRule;
    }
    
    public void setBooleanRule(String booleanRule) {
        this.booleanRule = booleanRule;
    }

    
    @Column(name="inModel")
    public Boolean getInModel() {
        return this.inModel;
    }
    
    public void setInModel(Boolean inModel) {
        this.inModel = inModel;
    }

    
    @Column(name="isGeneric")
    public Boolean getIsGeneric() {
        return this.isGeneric;
    }
    
    public void setIsGeneric(Boolean isGeneric) {
        this.isGeneric = isGeneric;
    }

    
    @Column(name="isSpontaneous")
    public Boolean getIsSpontaneous() {
        return this.isSpontaneous;
    }
    
    public void setIsSpontaneous(Boolean isSpontaneous) {
        this.isSpontaneous = isSpontaneous;
    }

    
    @Column(name="isNonEnzymatic")
    public Boolean getIsNonEnzymatic() {
        return this.isNonEnzymatic;
    }
    
    public void setIsNonEnzymatic(Boolean isNonEnzymatic) {
        this.isNonEnzymatic = isNonEnzymatic;
    }

    
    @Column(name="source", nullable=false, length=45)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="originalReaction", nullable=false)
    public boolean isOriginalReaction() {
        return this.originalReaction;
    }
    
    public void setOriginalReaction(boolean originalReaction) {
        this.originalReaction = originalReaction;
    }

    
    @Column(name="compartment_idcompartment")
    public Integer getCompartmentIdcompartment() {
        return this.compartmentIdcompartment;
    }
    
    public void setCompartmentIdcompartment(Integer compartmentIdcompartment) {
        this.compartmentIdcompartment = compartmentIdcompartment;
    }

    
    @Column(name="notes", length=65535)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="lowerBound", precision=12, scale=0)
    public Float getLowerBound() {
        return this.lowerBound;
    }
    
    public void setLowerBound(Float lowerBound) {
        this.lowerBound = lowerBound;
    }

    
    @Column(name="upperBound", precision=12, scale=0)
    public Float getUpperBound() {
        return this.upperBound;
    }
    
    public void setUpperBound(Float upperBound) {
        this.upperBound = upperBound;
    }




}


