package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ModelTranscriptionUnit generated by hbm2java
 */
@Entity
@Table(name = "model_transcription_unit", catalog = "sysbio_model")
public class ModelTranscriptionUnit implements java.io.Serializable {

	private Integer idtranscriptionUnit;
	private String name;
	private Set<ModelPromoter> modelPromoters = new HashSet<ModelPromoter>(0);
	private Set<ModelGene> modelGenes = new HashSet<ModelGene>(0);

	public ModelTranscriptionUnit() {
	}

	public ModelTranscriptionUnit(String name, Set<ModelPromoter> modelPromoters, Set<ModelGene> modelGenes) {
		this.name = name;
		this.modelPromoters = modelPromoters;
		this.modelGenes = modelGenes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtranscription_unit", unique = true, nullable = false)
	public Integer getIdtranscriptionUnit() {
		return this.idtranscriptionUnit;
	}

	public void setIdtranscriptionUnit(Integer idtranscriptionUnit) {
		this.idtranscriptionUnit = idtranscriptionUnit;
	}

	@Column(name = "name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "model_transcription_unit_promoter", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "transcription_unit_idtranscription_unit", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "promoter_idpromoter", nullable = false, updatable = false) })
	public Set<ModelPromoter> getModelPromoters() {
		return this.modelPromoters;
	}

	public void setModelPromoters(Set<ModelPromoter> modelPromoters) {
		this.modelPromoters = modelPromoters;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "model_transcription_unit_gene", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "transcription_unit_idtranscription_unit", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "gene_idgene", nullable = false, updatable = false) })
	public Set<ModelGene> getModelGenes() {
		return this.modelGenes;
	}

	public void setModelGenes(Set<ModelGene> modelGenes) {
		this.modelGenes = modelGenes;
	}

}
