package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelStoichiometry generated by hbm2java
 */
@Entity
@Table(name="model_stoichiometry"
    ,catalog="test_hibernate"
)
public class ModelStoichiometry  implements java.io.Serializable {


     private ModelStoichiometryId id;
     private float stoichiometricCoefficient;
     private String numberofchains;

    public ModelStoichiometry() {
    }

	
    public ModelStoichiometry(ModelStoichiometryId id, float stoichiometricCoefficient) {
        this.id = id;
        this.stoichiometricCoefficient = stoichiometricCoefficient;
    }
    public ModelStoichiometry(ModelStoichiometryId id, float stoichiometricCoefficient, String numberofchains) {
       this.id = id;
       this.stoichiometricCoefficient = stoichiometricCoefficient;
       this.numberofchains = numberofchains;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idstoichiometry", column=@Column(name="idstoichiometry", nullable=false) ), 
        @AttributeOverride(name="reactionIdreaction", column=@Column(name="reaction_idreaction", nullable=false) ), 
        @AttributeOverride(name="compoundIdcompound", column=@Column(name="compound_idcompound", nullable=false) ), 
        @AttributeOverride(name="compartmentIdcompartment", column=@Column(name="compartment_idcompartment", nullable=false) ) } )
    public ModelStoichiometryId getId() {
        return this.id;
    }
    
    public void setId(ModelStoichiometryId id) {
        this.id = id;
    }

    
    @Column(name="stoichiometric_coefficient", nullable=false, precision=12, scale=0)
    public float getStoichiometricCoefficient() {
        return this.stoichiometricCoefficient;
    }
    
    public void setStoichiometricCoefficient(float stoichiometricCoefficient) {
        this.stoichiometricCoefficient = stoichiometricCoefficient;
    }

    
    @Column(name="numberofchains", length=20)
    public String getNumberofchains() {
        return this.numberofchains;
    }
    
    public void setNumberofchains(String numberofchains) {
        this.numberofchains = numberofchains;
    }




}


