package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelProtein generated by hbm2java
 */
@Entity
@Table(name = "model_protein", catalog = "sysbio_model")
public class ModelProtein implements java.io.Serializable {

	private Integer idprotein;
	private String name;
	private String class_;
	private String inchi;
	private Float molecularWeight;
	private Float molecularWeightExp;
	private Float molecularWeightKd;
	private Float molecularWeightSeq;
	private Float pi;
	private Set<ModelMetabolicRegulation> modelMetabolicRegulations = new HashSet<ModelMetabolicRegulation>(0);
	private Set<ModelEnzymaticCofactor> modelEnzymaticCofactors = new HashSet<ModelEnzymaticCofactor>(0);
	private Set<ModelEnzymaticAlternativeCofactor> modelEnzymaticAlternativeCofactors = new HashSet<ModelEnzymaticAlternativeCofactor>(
			0);
	private Set<ModelFunctionalParameter> modelFunctionalParameters = new HashSet<ModelFunctionalParameter>(0);
	private Set<ModelCompound> modelCompounds = new HashSet<ModelCompound>(0);
	private Set<ModelPromoter> modelPromoters = new HashSet<ModelPromoter>(0);
	private Set<ModelProteinComposition> modelProteinCompositions = new HashSet<ModelProteinComposition>(0);
	private Set<ModelExperimentTurnoverNumber> modelExperimentTurnoverNumbers = new HashSet<ModelExperimentTurnoverNumber>(
			0);
	private Set<ModelExperimentSubstrateAffinity> modelExperimentSubstrateAffinities = new HashSet<ModelExperimentSubstrateAffinity>(
			0);
	private Set<ModelSubstrateAffinity> modelSubstrateAffinities = new HashSet<ModelSubstrateAffinity>(0);
	private Set<ModelRegulatoryEvent> modelRegulatoryEvents = new HashSet<ModelRegulatoryEvent>(0);
	private Set<ModelExperimentInhibitor> modelExperimentInhibitors = new HashSet<ModelExperimentInhibitor>(0);
	private Set<ModelEnzyme> modelEnzymes = new HashSet<ModelEnzyme>(0);

	public ModelProtein() {
	}

	public ModelProtein(String name) {
		this.name = name;
	}

	public ModelProtein(String name, String class_, String inchi, Float molecularWeight, Float molecularWeightExp,
			Float molecularWeightKd, Float molecularWeightSeq, Float pi,
			Set<ModelMetabolicRegulation> modelMetabolicRegulations,
			Set<ModelEnzymaticCofactor> modelEnzymaticCofactors,
			Set<ModelEnzymaticAlternativeCofactor> modelEnzymaticAlternativeCofactors,
			Set<ModelFunctionalParameter> modelFunctionalParameters, Set<ModelCompound> modelCompounds,
			Set<ModelPromoter> modelPromoters, Set<ModelProteinComposition> modelProteinCompositions,
			Set<ModelExperimentTurnoverNumber> modelExperimentTurnoverNumbers,
			Set<ModelExperimentSubstrateAffinity> modelExperimentSubstrateAffinities,
			Set<ModelSubstrateAffinity> modelSubstrateAffinities, Set<ModelRegulatoryEvent> modelRegulatoryEvents,
			Set<ModelExperimentInhibitor> modelExperimentInhibitors, Set<ModelEnzyme> modelEnzymes) {
		this.name = name;
		this.class_ = class_;
		this.inchi = inchi;
		this.molecularWeight = molecularWeight;
		this.molecularWeightExp = molecularWeightExp;
		this.molecularWeightKd = molecularWeightKd;
		this.molecularWeightSeq = molecularWeightSeq;
		this.pi = pi;
		this.modelMetabolicRegulations = modelMetabolicRegulations;
		this.modelEnzymaticCofactors = modelEnzymaticCofactors;
		this.modelEnzymaticAlternativeCofactors = modelEnzymaticAlternativeCofactors;
		this.modelFunctionalParameters = modelFunctionalParameters;
		this.modelCompounds = modelCompounds;
		this.modelPromoters = modelPromoters;
		this.modelProteinCompositions = modelProteinCompositions;
		this.modelExperimentTurnoverNumbers = modelExperimentTurnoverNumbers;
		this.modelExperimentSubstrateAffinities = modelExperimentSubstrateAffinities;
		this.modelSubstrateAffinities = modelSubstrateAffinities;
		this.modelRegulatoryEvents = modelRegulatoryEvents;
		this.modelExperimentInhibitors = modelExperimentInhibitors;
		this.modelEnzymes = modelEnzymes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idprotein", unique = true, nullable = false)
	public Integer getIdprotein() {
		return this.idprotein;
	}

	public void setIdprotein(Integer idprotein) {
		this.idprotein = idprotein;
	}

	@Column(name = "name", nullable = false, length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "class", length = 120)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "inchi")
	public String getInchi() {
		return this.inchi;
	}

	public void setInchi(String inchi) {
		this.inchi = inchi;
	}

	@Column(name = "molecular_weight", precision = 12, scale = 0)
	public Float getMolecularWeight() {
		return this.molecularWeight;
	}

	public void setMolecularWeight(Float molecularWeight) {
		this.molecularWeight = molecularWeight;
	}

	@Column(name = "molecular_weight_exp", precision = 12, scale = 0)
	public Float getMolecularWeightExp() {
		return this.molecularWeightExp;
	}

	public void setMolecularWeightExp(Float molecularWeightExp) {
		this.molecularWeightExp = molecularWeightExp;
	}

	@Column(name = "molecular_weight_kd", precision = 12, scale = 0)
	public Float getMolecularWeightKd() {
		return this.molecularWeightKd;
	}

	public void setMolecularWeightKd(Float molecularWeightKd) {
		this.molecularWeightKd = molecularWeightKd;
	}

	@Column(name = "molecular_weight_seq", precision = 12, scale = 0)
	public Float getMolecularWeightSeq() {
		return this.molecularWeightSeq;
	}

	public void setMolecularWeightSeq(Float molecularWeightSeq) {
		this.molecularWeightSeq = molecularWeightSeq;
	}

	@Column(name = "pi", precision = 12, scale = 0)
	public Float getPi() {
		return this.pi;
	}

	public void setPi(Float pi) {
		this.pi = pi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelMetabolicRegulation> getModelMetabolicRegulations() {
		return this.modelMetabolicRegulations;
	}

	public void setModelMetabolicRegulations(Set<ModelMetabolicRegulation> modelMetabolicRegulations) {
		this.modelMetabolicRegulations = modelMetabolicRegulations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelEnzymaticCofactor> getModelEnzymaticCofactors() {
		return this.modelEnzymaticCofactors;
	}

	public void setModelEnzymaticCofactors(Set<ModelEnzymaticCofactor> modelEnzymaticCofactors) {
		this.modelEnzymaticCofactors = modelEnzymaticCofactors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelEnzymaticAlternativeCofactor> getModelEnzymaticAlternativeCofactors() {
		return this.modelEnzymaticAlternativeCofactors;
	}

	public void setModelEnzymaticAlternativeCofactors(
			Set<ModelEnzymaticAlternativeCofactor> modelEnzymaticAlternativeCofactors) {
		this.modelEnzymaticAlternativeCofactors = modelEnzymaticAlternativeCofactors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelFunctionalParameter> getModelFunctionalParameters() {
		return this.modelFunctionalParameters;
	}

	public void setModelFunctionalParameters(Set<ModelFunctionalParameter> modelFunctionalParameters) {
		this.modelFunctionalParameters = modelFunctionalParameters;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "model_effector", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "protein_idprotein", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "compound_idcompound", nullable = false, updatable = false) })
	public Set<ModelCompound> getModelCompounds() {
		return this.modelCompounds;
	}

	public void setModelCompounds(Set<ModelCompound> modelCompounds) {
		this.modelCompounds = modelCompounds;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "model_sigma_promoter", catalog = "sysbio_model", joinColumns = {
			@JoinColumn(name = "protein_idprotein", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "promoter_idpromoter", nullable = false, updatable = false) })
	public Set<ModelPromoter> getModelPromoters() {
		return this.modelPromoters;
	}

	public void setModelPromoters(Set<ModelPromoter> modelPromoters) {
		this.modelPromoters = modelPromoters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelProteinComposition> getModelProteinCompositions() {
		return this.modelProteinCompositions;
	}

	public void setModelProteinCompositions(Set<ModelProteinComposition> modelProteinCompositions) {
		this.modelProteinCompositions = modelProteinCompositions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelExperimentTurnoverNumber> getModelExperimentTurnoverNumbers() {
		return this.modelExperimentTurnoverNumbers;
	}

	public void setModelExperimentTurnoverNumbers(Set<ModelExperimentTurnoverNumber> modelExperimentTurnoverNumbers) {
		this.modelExperimentTurnoverNumbers = modelExperimentTurnoverNumbers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelExperimentSubstrateAffinity> getModelExperimentSubstrateAffinities() {
		return this.modelExperimentSubstrateAffinities;
	}

	public void setModelExperimentSubstrateAffinities(
			Set<ModelExperimentSubstrateAffinity> modelExperimentSubstrateAffinities) {
		this.modelExperimentSubstrateAffinities = modelExperimentSubstrateAffinities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelSubstrateAffinity> getModelSubstrateAffinities() {
		return this.modelSubstrateAffinities;
	}

	public void setModelSubstrateAffinities(Set<ModelSubstrateAffinity> modelSubstrateAffinities) {
		this.modelSubstrateAffinities = modelSubstrateAffinities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelRegulatoryEvent> getModelRegulatoryEvents() {
		return this.modelRegulatoryEvents;
	}

	public void setModelRegulatoryEvents(Set<ModelRegulatoryEvent> modelRegulatoryEvents) {
		this.modelRegulatoryEvents = modelRegulatoryEvents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelExperimentInhibitor> getModelExperimentInhibitors() {
		return this.modelExperimentInhibitors;
	}

	public void setModelExperimentInhibitors(Set<ModelExperimentInhibitor> modelExperimentInhibitors) {
		this.modelExperimentInhibitors = modelExperimentInhibitors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelProtein")
	public Set<ModelEnzyme> getModelEnzymes() {
		return this.modelEnzymes;
	}

	public void setModelEnzymes(Set<ModelEnzyme> modelEnzymes) {
		this.modelEnzymes = modelEnzymes;
	}

}
