package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ModelSequenceFeature generated by hbm2java
 */
@Entity
@Table(name="model_sequence_feature"
    ,catalog="test_hibernate"
)
public class ModelSequenceFeature  implements java.io.Serializable {


     private int featureIdfeature;
     private int sequenceIdsequence;
     private String startPositionApproximate;
     private String endPositionApproximate;

    public ModelSequenceFeature() {
    }

	
    public ModelSequenceFeature(int featureIdfeature, int sequenceIdsequence) {
        this.featureIdfeature = featureIdfeature;
        this.sequenceIdsequence = sequenceIdsequence;
    }
    public ModelSequenceFeature(int featureIdfeature, int sequenceIdsequence, String startPositionApproximate, String endPositionApproximate) {
       this.featureIdfeature = featureIdfeature;
       this.sequenceIdsequence = sequenceIdsequence;
       this.startPositionApproximate = startPositionApproximate;
       this.endPositionApproximate = endPositionApproximate;
    }
   
     @Id 

    
    @Column(name="feature_idfeature", unique=true, nullable=false)
    public int getFeatureIdfeature() {
        return this.featureIdfeature;
    }
    
    public void setFeatureIdfeature(int featureIdfeature) {
        this.featureIdfeature = featureIdfeature;
    }

    
    @Column(name="sequence_idsequence", nullable=false)
    public int getSequenceIdsequence() {
        return this.sequenceIdsequence;
    }
    
    public void setSequenceIdsequence(int sequenceIdsequence) {
        this.sequenceIdsequence = sequenceIdsequence;
    }

    
    @Column(name="start_position_approximate", length=20)
    public String getStartPositionApproximate() {
        return this.startPositionApproximate;
    }
    
    public void setStartPositionApproximate(String startPositionApproximate) {
        this.startPositionApproximate = startPositionApproximate;
    }

    
    @Column(name="end_position_approximate", length=20)
    public String getEndPositionApproximate() {
        return this.endPositionApproximate;
    }
    
    public void setEndPositionApproximate(String endPositionApproximate) {
        this.endPositionApproximate = endPositionApproximate;
    }




}


