package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelSubstrateAffinity generated by hbm2java
 */
@Entity
@Table(name="model_substrate_affinity"
    ,catalog="test_hibernate"
)
public class ModelSubstrateAffinity  implements java.io.Serializable {


     private ModelSubstrateAffinityId id;
     private float substrateAffinity;

    public ModelSubstrateAffinity() {
    }

    public ModelSubstrateAffinity(ModelSubstrateAffinityId id, float substrateAffinity) {
       this.id = id;
       this.substrateAffinity = substrateAffinity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="compoundIdcompound", column=@Column(name="compound_idcompound", nullable=false) ), 
        @AttributeOverride(name="proteinIdprotein", column=@Column(name="protein_idprotein", nullable=false) ) } )
    public ModelSubstrateAffinityId getId() {
        return this.id;
    }
    
    public void setId(ModelSubstrateAffinityId id) {
        this.id = id;
    }

    
    @Column(name="substrate_affinity", nullable=false, precision=12, scale=0)
    public float getSubstrateAffinity() {
        return this.substrateAffinity;
    }
    
    public void setSubstrateAffinity(float substrateAffinity) {
        this.substrateAffinity = substrateAffinity;
    }




}


