package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelReactionHasEnzyme generated by hbm2java
 */
@Entity
@Table(name="model_reaction_has_enzyme"
    ,catalog="test_hibernate"
)
public class ModelReactionHasEnzyme  implements java.io.Serializable {


     private ModelReactionHasEnzymeId id;

    public ModelReactionHasEnzyme() {
    }

    public ModelReactionHasEnzyme(ModelReactionHasEnzymeId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="reactionIdreaction", column=@Column(name="reaction_idreaction", nullable=false) ), 
        @AttributeOverride(name="enzymeEcnumber", column=@Column(name="enzyme_ecnumber", nullable=false, length=15) ), 
        @AttributeOverride(name="enzymeProteinIdprotein", column=@Column(name="enzyme_protein_idprotein", nullable=false) ) } )
    public ModelReactionHasEnzymeId getId() {
        return this.id;
    }
    
    public void setId(ModelReactionHasEnzymeId id) {
        this.id = id;
    }




}


