package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModelExperimentTurnoverNumber generated by hbm2java
 */
@Entity
@Table(name = "model_experiment_turnover_number", catalog = "test_hibernate")
public class ModelExperimentTurnoverNumber implements java.io.Serializable {

	private ModelExperimentTurnoverNumberId id;
	private ModelCompound modelCompound;
	private ModelProtein modelProtein;
	private Float turnoverNumber;

	public ModelExperimentTurnoverNumber() {
	}

	public ModelExperimentTurnoverNumber(ModelExperimentTurnoverNumberId id, ModelCompound modelCompound,
			ModelProtein modelProtein) {
		this.id = id;
		this.modelCompound = modelCompound;
		this.modelProtein = modelProtein;
	}

	public ModelExperimentTurnoverNumber(ModelExperimentTurnoverNumberId id, ModelCompound modelCompound,
			ModelProtein modelProtein, Float turnoverNumber) {
		this.id = id;
		this.modelCompound = modelCompound;
		this.modelProtein = modelProtein;
		this.turnoverNumber = turnoverNumber;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "experimentDescription", column = @Column(name = "experiment_description", nullable = false)),
			@AttributeOverride(name = "compoundIdcompound", column = @Column(name = "compound_idcompound", nullable = false)),
			@AttributeOverride(name = "proteinIdprotein", column = @Column(name = "protein_idprotein", nullable = false)) })
	public ModelExperimentTurnoverNumberId getId() {
		return this.id;
	}

	public void setId(ModelExperimentTurnoverNumberId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compound_idcompound", nullable = false, insertable = false, updatable = false)
	public ModelCompound getModelCompound() {
		return this.modelCompound;
	}

	public void setModelCompound(ModelCompound modelCompound) {
		this.modelCompound = modelCompound;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "protein_idprotein", nullable = false, insertable = false, updatable = false)
	public ModelProtein getModelProtein() {
		return this.modelProtein;
	}

	public void setModelProtein(ModelProtein modelProtein) {
		this.modelProtein = modelProtein;
	}

	@Column(name = "turnover_number", precision = 12, scale = 0)
	public Float getTurnoverNumber() {
		return this.turnoverNumber;
	}

	public void setTurnoverNumber(Float turnoverNumber) {
		this.turnoverNumber = turnoverNumber;
	}

}
