package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModelStrain generated by hbm2java
 */
@Entity
@Table(name = "model_strain", catalog = "test_hibernate")
public class ModelStrain implements java.io.Serializable {

	private Integer idstrain;
	private String name;
	private Set<ModelEntityisfrom> modelEntityisfroms = new HashSet<ModelEntityisfrom>(0);

	public ModelStrain() {
	}

	public ModelStrain(String name, Set<ModelEntityisfrom> modelEntityisfroms) {
		this.name = name;
		this.modelEntityisfroms = modelEntityisfroms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idstrain", unique = true, nullable = false)
	public Integer getIdstrain() {
		return this.idstrain;
	}

	public void setIdstrain(Integer idstrain) {
		this.idstrain = idstrain;
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelStrain")
	public Set<ModelEntityisfrom> getModelEntityisfroms() {
		return this.modelEntityisfroms;
	}

	public void setModelEntityisfroms(Set<ModelEntityisfrom> modelEntityisfroms) {
		this.modelEntityisfroms = modelEntityisfroms;
	}

}
