package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelSubunit generated by hbm2java
 */
@Entity
@Table(name="model_subunit"
    ,catalog="test_hibernate"
)
public class ModelSubunit  implements java.io.Serializable {


     private ModelSubunitId id;

    public ModelSubunit() {
    }

    public ModelSubunit(ModelSubunitId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="geneIdgene", column=@Column(name="gene_idgene", nullable=false) ), 
        @AttributeOverride(name="enzymeProteinIdprotein", column=@Column(name="enzyme_protein_idprotein", nullable=false) ), 
        @AttributeOverride(name="enzymeEcnumber", column=@Column(name="enzyme_ecnumber", nullable=false, length=15) ) } )
    public ModelSubunitId getId() {
        return this.id;
    }
    
    public void setId(ModelSubunitId id) {
        this.id = id;
    }




}


