package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelPathwayHasCompound generated by hbm2java
 */
@Entity
@Table(name="model_pathway_has_compound"
    ,catalog="test_hibernate"
)
public class ModelPathwayHasCompound  implements java.io.Serializable {


     private ModelPathwayHasCompoundId id;

    public ModelPathwayHasCompound() {
    }

    public ModelPathwayHasCompound(ModelPathwayHasCompoundId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pathwayIdpathway", column=@Column(name="pathway_idpathway", nullable=false) ), 
        @AttributeOverride(name="compoundIdcompound", column=@Column(name="compound_idcompound", nullable=false) ) } )
    public ModelPathwayHasCompoundId getId() {
        return this.id;
    }
    
    public void setId(ModelPathwayHasCompoundId id) {
        this.id = id;
    }




}


