package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelAliasesId generated by hbm2java
 */
@Embeddable
public class ModelAliasesId  implements java.io.Serializable {


     private int idalias;
     private String class_;
     private int entity;

    public ModelAliasesId() {
    }

    public ModelAliasesId(int idalias, String class_, int entity) {
       this.idalias = idalias;
       this.class_ = class_;
       this.entity = entity;
    }
   


    @Column(name="idalias", nullable=false)
    public int getIdalias() {
        return this.idalias;
    }
    
    public void setIdalias(int idalias) {
        this.idalias = idalias;
    }


    @Column(name="class", nullable=false, length=2)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }


    @Column(name="entity", nullable=false)
    public int getEntity() {
        return this.entity;
    }
    
    public void setEntity(int entity) {
        this.entity = entity;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelAliasesId) ) return false;
		 ModelAliasesId castOther = ( ModelAliasesId ) other; 
         
		 return (this.getIdalias()==castOther.getIdalias())
 && ( (this.getClass_()==castOther.getClass_()) || ( this.getClass_()!=null && castOther.getClass_()!=null && this.getClass_().equals(castOther.getClass_()) ) )
 && (this.getEntity()==castOther.getEntity());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdalias();
         result = 37 * result + ( getClass_() == null ? 0 : this.getClass_().hashCode() );
         result = 37 * result + this.getEntity();
         return result;
   }   


}


