package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelEnzymaticAlternativeCofactor generated by hbm2java
 */
@Entity
@Table(name="model_enzymatic_alternative_cofactor"
    ,catalog="test_hibernate"
)
public class ModelEnzymaticAlternativeCofactor  implements java.io.Serializable {


     private ModelEnzymaticAlternativeCofactorId id;

    public ModelEnzymaticAlternativeCofactor() {
    }

    public ModelEnzymaticAlternativeCofactor(ModelEnzymaticAlternativeCofactorId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="compoundIdcompound", column=@Column(name="compound_idcompound", nullable=false) ), 
        @AttributeOverride(name="originalCofactor", column=@Column(name="original_cofactor", nullable=false) ), 
        @AttributeOverride(name="proteinIdprotein", column=@Column(name="protein_idprotein", nullable=false) ) } )
    public ModelEnzymaticAlternativeCofactorId getId() {
        return this.id;
    }
    
    public void setId(ModelEnzymaticAlternativeCofactorId id) {
        this.id = id;
    }




}


