package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModelSubunit generated by hbm2java
 */
@Entity
@Table(name = "model_subunit", catalog = "sysbio_model")
public class ModelSubunit implements java.io.Serializable {

	private ModelSubunitId id;
	private ModelEnzyme modelEnzyme;
	private ModelGene modelGene;

	public ModelSubunit() {
	}

	public ModelSubunit(ModelSubunitId id, ModelEnzyme modelEnzyme, ModelGene modelGene) {
		this.id = id;
		this.modelEnzyme = modelEnzyme;
		this.modelGene = modelGene;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "geneIdgene", column = @Column(name = "gene_idgene", nullable = false)),
			@AttributeOverride(name = "enzymeProteinIdprotein", column = @Column(name = "enzyme_protein_idprotein", nullable = false)),
			@AttributeOverride(name = "enzymeEcnumber", column = @Column(name = "enzyme_ecnumber", nullable = false, length = 15)) })
	public ModelSubunitId getId() {
		return this.id;
	}

	public void setId(ModelSubunitId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "enzyme_ecnumber", referencedColumnName = "ecnumber", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "enzyme_protein_idprotein", referencedColumnName = "protein_idprotein", nullable = false, insertable = false, updatable = false) })
	public ModelEnzyme getModelEnzyme() {
		return this.modelEnzyme;
	}

	public void setModelEnzyme(ModelEnzyme modelEnzyme) {
		this.modelEnzyme = modelEnzyme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gene_idgene", nullable = false, insertable = false, updatable = false)
	public ModelGene getModelGene() {
		return this.modelGene;
	}

	public void setModelGene(ModelGene modelGene) {
		this.modelGene = modelGene;
	}

}
