package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelExperimentTurnoverNumber generated by hbm2java
 */
@Entity
@Table(name="model_experiment_turnover_number"
    ,catalog="test_hibernate"
)
public class ModelExperimentTurnoverNumber  implements java.io.Serializable {


     private ModelExperimentTurnoverNumberId id;
     private Float turnoverNumber;

    public ModelExperimentTurnoverNumber() {
    }

	
    public ModelExperimentTurnoverNumber(ModelExperimentTurnoverNumberId id) {
        this.id = id;
    }
    public ModelExperimentTurnoverNumber(ModelExperimentTurnoverNumberId id, Float turnoverNumber) {
       this.id = id;
       this.turnoverNumber = turnoverNumber;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="experimentDescription", column=@Column(name="experiment_description", nullable=false) ), 
        @AttributeOverride(name="compoundIdcompound", column=@Column(name="compound_idcompound", nullable=false) ), 
        @AttributeOverride(name="proteinIdprotein", column=@Column(name="protein_idprotein", nullable=false) ) } )
    public ModelExperimentTurnoverNumberId getId() {
        return this.id;
    }
    
    public void setId(ModelExperimentTurnoverNumberId id) {
        this.id = id;
    }

    
    @Column(name="turnover_number", precision=12, scale=0)
    public Float getTurnoverNumber() {
        return this.turnoverNumber;
    }
    
    public void setTurnoverNumber(Float turnoverNumber) {
        this.turnoverNumber = turnoverNumber;
    }




}


