package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModelEnzymeHasModule generated by hbm2java
 */
@Entity
@Table(name = "model_enzyme_has_module", catalog = "sysbio_model")
public class ModelEnzymeHasModule implements java.io.Serializable {

	private ModelEnzymeHasModuleId id;
	private ModelEnzyme modelEnzyme;
	private ModelModule modelModule;
	private String name;
	private String note;

	public ModelEnzymeHasModule() {
	}

	public ModelEnzymeHasModule(ModelEnzymeHasModuleId id, ModelEnzyme modelEnzyme, ModelModule modelModule) {
		this.id = id;
		this.modelEnzyme = modelEnzyme;
		this.modelModule = modelModule;
	}

	public ModelEnzymeHasModule(ModelEnzymeHasModuleId id, ModelEnzyme modelEnzyme, ModelModule modelModule,
			String name, String note) {
		this.id = id;
		this.modelEnzyme = modelEnzyme;
		this.modelModule = modelModule;
		this.name = name;
		this.note = note;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "enzymeEcnumber", column = @Column(name = "enzyme_ecnumber", nullable = false, length = 15)),
			@AttributeOverride(name = "enzymeProteinIdprotein", column = @Column(name = "enzyme_protein_idprotein", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)) })
	public ModelEnzymeHasModuleId getId() {
		return this.id;
	}

	public void setId(ModelEnzymeHasModuleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "enzyme_ecnumber", referencedColumnName = "ecnumber", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "enzyme_protein_idprotein", referencedColumnName = "protein_idprotein", nullable = false, insertable = false, updatable = false) })
	public ModelEnzyme getModelEnzyme() {
		return this.modelEnzyme;
	}

	public void setModelEnzyme(ModelEnzyme modelEnzyme) {
		this.modelEnzyme = modelEnzyme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id", nullable = false, insertable = false, updatable = false)
	public ModelModule getModelModule() {
		return this.modelModule;
	}

	public void setModelModule(ModelModule modelModule) {
		this.modelModule = modelModule;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
