package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelEnzymaticAlternativeCofactorId generated by hbm2java
 */
@Embeddable
public class ModelEnzymaticAlternativeCofactorId  implements java.io.Serializable {


     private int compoundIdcompound;
     private int originalCofactor;
     private int proteinIdprotein;

    public ModelEnzymaticAlternativeCofactorId() {
    }

    public ModelEnzymaticAlternativeCofactorId(int compoundIdcompound, int originalCofactor, int proteinIdprotein) {
       this.compoundIdcompound = compoundIdcompound;
       this.originalCofactor = originalCofactor;
       this.proteinIdprotein = proteinIdprotein;
    }
   


    @Column(name="compound_idcompound", nullable=false)
    public int getCompoundIdcompound() {
        return this.compoundIdcompound;
    }
    
    public void setCompoundIdcompound(int compoundIdcompound) {
        this.compoundIdcompound = compoundIdcompound;
    }


    @Column(name="original_cofactor", nullable=false)
    public int getOriginalCofactor() {
        return this.originalCofactor;
    }
    
    public void setOriginalCofactor(int originalCofactor) {
        this.originalCofactor = originalCofactor;
    }


    @Column(name="protein_idprotein", nullable=false)
    public int getProteinIdprotein() {
        return this.proteinIdprotein;
    }
    
    public void setProteinIdprotein(int proteinIdprotein) {
        this.proteinIdprotein = proteinIdprotein;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModelEnzymaticAlternativeCofactorId) ) return false;
		 ModelEnzymaticAlternativeCofactorId castOther = ( ModelEnzymaticAlternativeCofactorId ) other; 
         
		 return (this.getCompoundIdcompound()==castOther.getCompoundIdcompound())
 && (this.getOriginalCofactor()==castOther.getOriginalCofactor())
 && (this.getProteinIdprotein()==castOther.getProteinIdprotein());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCompoundIdcompound();
         result = 37 * result + this.getOriginalCofactor();
         result = 37 * result + this.getProteinIdprotein();
         return result;
   }   


}


