package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransportersAnnotationGenesHasMetabolitesHasType generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_genes_has_metabolites_has_type", catalog = "test_hibernate")
public class TransportersAnnotationGenesHasMetabolitesHasType implements java.io.Serializable {

	private TransportersAnnotationGenesHasMetabolitesHasTypeId id;
	private TransportersAnnotationGenesHasMetabolites transportersAnnotationGenesHasMetabolites;
	private TransportersAnnotationTransportTypes transportersAnnotationTransportTypes;
	private float transportTypeScoreSum;
	private float taxonomyScoreSum;
	private int frequency;

	public TransportersAnnotationGenesHasMetabolitesHasType() {
	}

	public TransportersAnnotationGenesHasMetabolitesHasType(TransportersAnnotationGenesHasMetabolitesHasTypeId id,
			TransportersAnnotationGenesHasMetabolites transportersAnnotationGenesHasMetabolites,
			TransportersAnnotationTransportTypes transportersAnnotationTransportTypes, float transportTypeScoreSum,
			float taxonomyScoreSum, int frequency) {
		this.id = id;
		this.transportersAnnotationGenesHasMetabolites = transportersAnnotationGenesHasMetabolites;
		this.transportersAnnotationTransportTypes = transportersAnnotationTransportTypes;
		this.transportTypeScoreSum = transportTypeScoreSum;
		this.taxonomyScoreSum = taxonomyScoreSum;
		this.frequency = frequency;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "geneId", column = @Column(name = "gene_id", nullable = false)),
			@AttributeOverride(name = "transportTypeId", column = @Column(name = "transport_type_id", nullable = false)),
			@AttributeOverride(name = "metaboliteId", column = @Column(name = "metabolite_id", nullable = false)) })
	public TransportersAnnotationGenesHasMetabolitesHasTypeId getId() {
		return this.id;
	}

	public void setId(TransportersAnnotationGenesHasMetabolitesHasTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "gene_id", referencedColumnName = "gene_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "metabolite_id", referencedColumnName = "metabolite_id", nullable = false, insertable = false, updatable = false) })
	public TransportersAnnotationGenesHasMetabolites getTransportersAnnotationGenesHasMetabolites() {
		return this.transportersAnnotationGenesHasMetabolites;
	}

	public void setTransportersAnnotationGenesHasMetabolites(
			TransportersAnnotationGenesHasMetabolites transportersAnnotationGenesHasMetabolites) {
		this.transportersAnnotationGenesHasMetabolites = transportersAnnotationGenesHasMetabolites;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transport_type_id", nullable = false, insertable = false, updatable = false)
	public TransportersAnnotationTransportTypes getTransportersAnnotationTransportTypes() {
		return this.transportersAnnotationTransportTypes;
	}

	public void setTransportersAnnotationTransportTypes(
			TransportersAnnotationTransportTypes transportersAnnotationTransportTypes) {
		this.transportersAnnotationTransportTypes = transportersAnnotationTransportTypes;
	}

	@Column(name = "transport_type_score_sum", nullable = false, precision = 12, scale = 0)
	public float getTransportTypeScoreSum() {
		return this.transportTypeScoreSum;
	}

	public void setTransportTypeScoreSum(float transportTypeScoreSum) {
		this.transportTypeScoreSum = transportTypeScoreSum;
	}

	@Column(name = "taxonomy_score_sum", nullable = false, precision = 12, scale = 0)
	public float getTaxonomyScoreSum() {
		return this.taxonomyScoreSum;
	}

	public void setTaxonomyScoreSum(float taxonomyScoreSum) {
		this.taxonomyScoreSum = taxonomyScoreSum;
	}

	@Column(name = "frequency", nullable = false)
	public int getFrequency() {
		return this.frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

}
