package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TransportersIdentificationProjects generated by hbm2java
 */
@Entity
@Table(name="transporters_identification_projects"
    ,catalog="test_hibernate"
)
public class TransportersIdentificationProjects  implements java.io.Serializable {


     private Integer id;
     private int version;
     private int organismId;
     private boolean latestVersion;
     private Date date;
     private String organismName;
     private String organismLineage;
     private String compartmentsTool;

    public TransportersIdentificationProjects() {
    }

	
    public TransportersIdentificationProjects(int organismId, boolean latestVersion, Date date) {
        this.organismId = organismId;
        this.latestVersion = latestVersion;
        this.date = date;
    }
    public TransportersIdentificationProjects(int organismId, boolean latestVersion, Date date, String organismName, String organismLineage, String compartmentsTool) {
       this.organismId = organismId;
       this.latestVersion = latestVersion;
       this.date = date;
       this.organismName = organismName;
       this.organismLineage = organismLineage;
       this.compartmentsTool = compartmentsTool;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    
    @Column(name="organism_id", nullable=false)
    public int getOrganismId() {
        return this.organismId;
    }
    
    public void setOrganismId(int organismId) {
        this.organismId = organismId;
    }

    
    @Column(name="latest_version", nullable=false)
    public boolean isLatestVersion() {
        return this.latestVersion;
    }
    
    public void setLatestVersion(boolean latestVersion) {
        this.latestVersion = latestVersion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="organism_name", length=200)
    public String getOrganismName() {
        return this.organismName;
    }
    
    public void setOrganismName(String organismName) {
        this.organismName = organismName;
    }

    
    @Column(name="organism_lineage", length=1000)
    public String getOrganismLineage() {
        return this.organismLineage;
    }
    
    public void setOrganismLineage(String organismLineage) {
        this.organismLineage = organismLineage;
    }

    
    @Column(name="compartments_tool", length=60)
    public String getCompartmentsTool() {
        return this.compartmentsTool;
    }
    
    public void setCompartmentsTool(String compartmentsTool) {
        this.compartmentsTool = compartmentsTool;
    }




}


