package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransportersIdentificationSwSimilaritiesId generated by hbm2java
 */
@Embeddable
public class TransportersIdentificationSwSimilaritiesId  implements java.io.Serializable {


     private int swReportId;
     private int swHitId;

    public TransportersIdentificationSwSimilaritiesId() {
    }

    public TransportersIdentificationSwSimilaritiesId(int swReportId, int swHitId) {
       this.swReportId = swReportId;
       this.swHitId = swHitId;
    }
   


    @Column(name="sw_report_id", nullable=false)
    public int getSwReportId() {
        return this.swReportId;
    }
    
    public void setSwReportId(int swReportId) {
        this.swReportId = swReportId;
    }


    @Column(name="sw_hit_id", nullable=false)
    public int getSwHitId() {
        return this.swHitId;
    }
    
    public void setSwHitId(int swHitId) {
        this.swHitId = swHitId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransportersIdentificationSwSimilaritiesId) ) return false;
		 TransportersIdentificationSwSimilaritiesId castOther = ( TransportersIdentificationSwSimilaritiesId ) other; 
         
		 return (this.getSwReportId()==castOther.getSwReportId())
 && (this.getSwHitId()==castOther.getSwHitId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSwReportId();
         result = 37 * result + this.getSwHitId();
         return result;
   }   


}


