package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransportersAnnotationTransportTypes generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_transport_types", catalog = "sysbio_model")
public class TransportersAnnotationTransportTypes implements java.io.Serializable {

	private Integer id;
	private String name;
	private String directions;
	private Boolean reversible;
	private Set<TransportersAnnotationGenesHasMetabolitesHasType> transportersAnnotationGenesHasMetabolitesHasTypes = new HashSet<TransportersAnnotationGenesHasMetabolitesHasType>(
			0);
	private Set<TransportersAnnotationTransportSystems> transportersAnnotationTransportSystemses = new HashSet<TransportersAnnotationTransportSystems>(
			0);

	public TransportersAnnotationTransportTypes() {
	}

	public TransportersAnnotationTransportTypes(String name, String directions, Boolean reversible,
			Set<TransportersAnnotationGenesHasMetabolitesHasType> transportersAnnotationGenesHasMetabolitesHasTypes,
			Set<TransportersAnnotationTransportSystems> transportersAnnotationTransportSystemses) {
		this.name = name;
		this.directions = directions;
		this.reversible = reversible;
		this.transportersAnnotationGenesHasMetabolitesHasTypes = transportersAnnotationGenesHasMetabolitesHasTypes;
		this.transportersAnnotationTransportSystemses = transportersAnnotationTransportSystemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "directions", length = 45)
	public String getDirections() {
		return this.directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	@Column(name = "reversible")
	public Boolean getReversible() {
		return this.reversible;
	}

	public void setReversible(Boolean reversible) {
		this.reversible = reversible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationTransportTypes")
	public Set<TransportersAnnotationGenesHasMetabolitesHasType> getTransportersAnnotationGenesHasMetabolitesHasTypes() {
		return this.transportersAnnotationGenesHasMetabolitesHasTypes;
	}

	public void setTransportersAnnotationGenesHasMetabolitesHasTypes(
			Set<TransportersAnnotationGenesHasMetabolitesHasType> transportersAnnotationGenesHasMetabolitesHasTypes) {
		this.transportersAnnotationGenesHasMetabolitesHasTypes = transportersAnnotationGenesHasMetabolitesHasTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationTransportTypes")
	public Set<TransportersAnnotationTransportSystems> getTransportersAnnotationTransportSystemses() {
		return this.transportersAnnotationTransportSystemses;
	}

	public void setTransportersAnnotationTransportSystemses(
			Set<TransportersAnnotationTransportSystems> transportersAnnotationTransportSystemses) {
		this.transportersAnnotationTransportSystemses = transportersAnnotationTransportSystemses;
	}

}
