package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TransportersAnnotationGenesHasMetabolitesHasType generated by hbm2java
 */
@Entity
@Table(name="transporters_annotation_genes_has_metabolites_has_type"
    ,catalog="test_hibernate"
)
public class TransportersAnnotationGenesHasMetabolitesHasType  implements java.io.Serializable {


     private TransportersAnnotationGenesHasMetabolitesHasTypeId id;
     private float transportTypeScoreSum;
     private float taxonomyScoreSum;
     private int frequency;

    public TransportersAnnotationGenesHasMetabolitesHasType() {
    }

    public TransportersAnnotationGenesHasMetabolitesHasType(TransportersAnnotationGenesHasMetabolitesHasTypeId id, float transportTypeScoreSum, float taxonomyScoreSum, int frequency) {
       this.id = id;
       this.transportTypeScoreSum = transportTypeScoreSum;
       this.taxonomyScoreSum = taxonomyScoreSum;
       this.frequency = frequency;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="geneId", column=@Column(name="gene_id", nullable=false) ), 
        @AttributeOverride(name="transportTypeId", column=@Column(name="transport_type_id", nullable=false) ), 
        @AttributeOverride(name="metaboliteId", column=@Column(name="metabolite_id", nullable=false) ) } )
    public TransportersAnnotationGenesHasMetabolitesHasTypeId getId() {
        return this.id;
    }
    
    public void setId(TransportersAnnotationGenesHasMetabolitesHasTypeId id) {
        this.id = id;
    }

    
    @Column(name="transport_type_score_sum", nullable=false, precision=12, scale=0)
    public float getTransportTypeScoreSum() {
        return this.transportTypeScoreSum;
    }
    
    public void setTransportTypeScoreSum(float transportTypeScoreSum) {
        this.transportTypeScoreSum = transportTypeScoreSum;
    }

    
    @Column(name="taxonomy_score_sum", nullable=false, precision=12, scale=0)
    public float getTaxonomyScoreSum() {
        return this.taxonomyScoreSum;
    }
    
    public void setTaxonomyScoreSum(float taxonomyScoreSum) {
        this.taxonomyScoreSum = taxonomyScoreSum;
    }

    
    @Column(name="frequency", nullable=false)
    public int getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(int frequency) {
        this.frequency = frequency;
    }




}


