package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransportersIdentificationSwReports generated by hbm2java
 */
@Entity
@Table(name = "transporters_identification_sw_reports", catalog = "test_hibernate")
public class TransportersIdentificationSwReports implements java.io.Serializable {

	private Integer id;
	private TransportersIdentificationProjects transportersIdentificationProjects;
	private String locusTag;
	private Date date;
	private String matrix;
	private int numberTmd;
	private String status;
	private Set<TransportersIdentificationSwSimilarities> transportersIdentificationSwSimilaritieses = new HashSet<TransportersIdentificationSwSimilarities>(
			0);

	public TransportersIdentificationSwReports() {
	}

	public TransportersIdentificationSwReports(TransportersIdentificationProjects transportersIdentificationProjects,
			String locusTag, Date date, int numberTmd) {
		this.transportersIdentificationProjects = transportersIdentificationProjects;
		this.locusTag = locusTag;
		this.date = date;
		this.numberTmd = numberTmd;
	}

	public TransportersIdentificationSwReports(TransportersIdentificationProjects transportersIdentificationProjects,
			String locusTag, Date date, String matrix, int numberTmd, String status,
			Set<TransportersIdentificationSwSimilarities> transportersIdentificationSwSimilaritieses) {
		this.transportersIdentificationProjects = transportersIdentificationProjects;
		this.locusTag = locusTag;
		this.date = date;
		this.matrix = matrix;
		this.numberTmd = numberTmd;
		this.status = status;
		this.transportersIdentificationSwSimilaritieses = transportersIdentificationSwSimilaritieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public TransportersIdentificationProjects getTransportersIdentificationProjects() {
		return this.transportersIdentificationProjects;
	}

	public void setTransportersIdentificationProjects(
			TransportersIdentificationProjects transportersIdentificationProjects) {
		this.transportersIdentificationProjects = transportersIdentificationProjects;
	}

	@Column(name = "locus_tag", nullable = false, length = 100)
	public String getLocusTag() {
		return this.locusTag;
	}

	public void setLocusTag(String locusTag) {
		this.locusTag = locusTag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "matrix", length = 45)
	public String getMatrix() {
		return this.matrix;
	}

	public void setMatrix(String matrix) {
		this.matrix = matrix;
	}

	@Column(name = "number_TMD", nullable = false)
	public int getNumberTmd() {
		return this.numberTmd;
	}

	public void setNumberTmd(int numberTmd) {
		this.numberTmd = numberTmd;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersIdentificationSwReports")
	public Set<TransportersIdentificationSwSimilarities> getTransportersIdentificationSwSimilaritieses() {
		return this.transportersIdentificationSwSimilaritieses;
	}

	public void setTransportersIdentificationSwSimilaritieses(
			Set<TransportersIdentificationSwSimilarities> transportersIdentificationSwSimilaritieses) {
		this.transportersIdentificationSwSimilaritieses = transportersIdentificationSwSimilaritieses;
	}

}
