package hibernate.merlin_hibernate.entities;
// Generated 21/mar/2018 18:06:35 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TransportersAnnotationTcNumbersHasTransportSystems generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_tc_numbers_has_transport_systems", catalog = "test_hibernate")
public class TransportersAnnotationTcNumbersHasTransportSystems implements java.io.Serializable {

	private TransportersAnnotationTcNumbersHasTransportSystemsId id;

	public TransportersAnnotationTcNumbersHasTransportSystems() {
	}

	public TransportersAnnotationTcNumbersHasTransportSystems(TransportersAnnotationTcNumbersHasTransportSystemsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "transportSystemId", column = @Column(name = "transport_system_id", nullable = false)),
			@AttributeOverride(name = "tcNumber", column = @Column(name = "tc_number", nullable = false, length = 45)),
			@AttributeOverride(name = "tcVersion", column = @Column(name = "tc_version", nullable = false)) })
	public TransportersAnnotationTcNumbersHasTransportSystemsId getId() {
		return this.id;
	}

	public void setId(TransportersAnnotationTcNumbersHasTransportSystemsId id) {
		this.id = id;
	}

}
