package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransportersAnnotationTaxonomyData generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_taxonomy_data", catalog = "test_hibernate")
public class TransportersAnnotationTaxonomyData implements java.io.Serializable {

	private Integer id;
	private String organism;
	private String taxonomy;
	private Set<TransportersAnnotationTcNumbers> transportersAnnotationTcNumberses = new HashSet<TransportersAnnotationTcNumbers>(
			0);

	public TransportersAnnotationTaxonomyData() {
	}

	public TransportersAnnotationTaxonomyData(String organism, String taxonomy,
			Set<TransportersAnnotationTcNumbers> transportersAnnotationTcNumberses) {
		this.organism = organism;
		this.taxonomy = taxonomy;
		this.transportersAnnotationTcNumberses = transportersAnnotationTcNumberses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "organism", length = 65535)
	public String getOrganism() {
		return this.organism;
	}

	public void setOrganism(String organism) {
		this.organism = organism;
	}

	@Column(name = "taxonomy", length = 65535)
	public String getTaxonomy() {
		return this.taxonomy;
	}

	public void setTaxonomy(String taxonomy) {
		this.taxonomy = taxonomy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationTaxonomyData")
	public Set<TransportersAnnotationTcNumbers> getTransportersAnnotationTcNumberses() {
		return this.transportersAnnotationTcNumberses;
	}

	public void setTransportersAnnotationTcNumberses(
			Set<TransportersAnnotationTcNumbers> transportersAnnotationTcNumberses) {
		this.transportersAnnotationTcNumberses = transportersAnnotationTcNumberses;
	}

}
