package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransportersAnnotationTcdbRegistries generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_tcdb_registries", catalog = "sysbio_model")
public class TransportersAnnotationTcdbRegistries implements java.io.Serializable {

	private TransportersAnnotationTcdbRegistriesId id;
	private TransportersAnnotationTcNumbers transportersAnnotationTcNumbers;
	private Date loadedAt;
	private boolean latestVersion;
	private String status;
	private Set<TransportersAnnotationGenesHasTcdbRegistries> transportersAnnotationGenesHasTcdbRegistrieses = new HashSet<TransportersAnnotationGenesHasTcdbRegistries>(
			0);

	public TransportersAnnotationTcdbRegistries() {
	}

	public TransportersAnnotationTcdbRegistries(TransportersAnnotationTcdbRegistriesId id,
			TransportersAnnotationTcNumbers transportersAnnotationTcNumbers, Date loadedAt, boolean latestVersion,
			String status) {
		this.id = id;
		this.transportersAnnotationTcNumbers = transportersAnnotationTcNumbers;
		this.loadedAt = loadedAt;
		this.latestVersion = latestVersion;
		this.status = status;
	}

	public TransportersAnnotationTcdbRegistries(TransportersAnnotationTcdbRegistriesId id,
			TransportersAnnotationTcNumbers transportersAnnotationTcNumbers, Date loadedAt, boolean latestVersion,
			String status,
			Set<TransportersAnnotationGenesHasTcdbRegistries> transportersAnnotationGenesHasTcdbRegistrieses) {
		this.id = id;
		this.transportersAnnotationTcNumbers = transportersAnnotationTcNumbers;
		this.loadedAt = loadedAt;
		this.latestVersion = latestVersion;
		this.status = status;
		this.transportersAnnotationGenesHasTcdbRegistrieses = transportersAnnotationGenesHasTcdbRegistrieses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "uniprotId", column = @Column(name = "uniprot_id", nullable = false, length = 45)),
			@AttributeOverride(name = "version", column = @Column(name = "version", nullable = false)) })
	public TransportersAnnotationTcdbRegistriesId getId() {
		return this.id;
	}

	public void setId(TransportersAnnotationTcdbRegistriesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "tc_number", referencedColumnName = "tc_number", nullable = false),
			@JoinColumn(name = "tc_version", referencedColumnName = "tc_version", nullable = false) })
	public TransportersAnnotationTcNumbers getTransportersAnnotationTcNumbers() {
		return this.transportersAnnotationTcNumbers;
	}

	public void setTransportersAnnotationTcNumbers(TransportersAnnotationTcNumbers transportersAnnotationTcNumbers) {
		this.transportersAnnotationTcNumbers = transportersAnnotationTcNumbers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loaded_at", nullable = false, length = 19)
	public Date getLoadedAt() {
		return this.loadedAt;
	}

	public void setLoadedAt(Date loadedAt) {
		this.loadedAt = loadedAt;
	}

	@Column(name = "latest_version", nullable = false)
	public boolean isLatestVersion() {
		return this.latestVersion;
	}

	public void setLatestVersion(boolean latestVersion) {
		this.latestVersion = latestVersion;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationTcdbRegistries")
	public Set<TransportersAnnotationGenesHasTcdbRegistries> getTransportersAnnotationGenesHasTcdbRegistrieses() {
		return this.transportersAnnotationGenesHasTcdbRegistrieses;
	}

	public void setTransportersAnnotationGenesHasTcdbRegistrieses(
			Set<TransportersAnnotationGenesHasTcdbRegistries> transportersAnnotationGenesHasTcdbRegistrieses) {
		this.transportersAnnotationGenesHasTcdbRegistrieses = transportersAnnotationGenesHasTcdbRegistrieses;
	}

}
