package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransportersIdentificationSwSimilarities generated by hbm2java
 */
@Entity
@Table(name = "transporters_identification_sw_similarities", catalog = "test_hibernate")
public class TransportersIdentificationSwSimilarities implements java.io.Serializable {

	private TransportersIdentificationSwSimilaritiesId id;
	private TransportersIdentificationSwHits transportersIdentificationSwHits;
	private TransportersIdentificationSwReports transportersIdentificationSwReports;
	private Float similarity;

	public TransportersIdentificationSwSimilarities() {
	}

	public TransportersIdentificationSwSimilarities(TransportersIdentificationSwSimilaritiesId id,
			TransportersIdentificationSwHits transportersIdentificationSwHits,
			TransportersIdentificationSwReports transportersIdentificationSwReports) {
		this.id = id;
		this.transportersIdentificationSwHits = transportersIdentificationSwHits;
		this.transportersIdentificationSwReports = transportersIdentificationSwReports;
	}

	public TransportersIdentificationSwSimilarities(TransportersIdentificationSwSimilaritiesId id,
			TransportersIdentificationSwHits transportersIdentificationSwHits,
			TransportersIdentificationSwReports transportersIdentificationSwReports, Float similarity) {
		this.id = id;
		this.transportersIdentificationSwHits = transportersIdentificationSwHits;
		this.transportersIdentificationSwReports = transportersIdentificationSwReports;
		this.similarity = similarity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "swReportId", column = @Column(name = "sw_report_id", nullable = false)),
			@AttributeOverride(name = "swHitId", column = @Column(name = "sw_hit_id", nullable = false)) })
	public TransportersIdentificationSwSimilaritiesId getId() {
		return this.id;
	}

	public void setId(TransportersIdentificationSwSimilaritiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sw_hit_id", nullable = false, insertable = false, updatable = false)
	public TransportersIdentificationSwHits getTransportersIdentificationSwHits() {
		return this.transportersIdentificationSwHits;
	}

	public void setTransportersIdentificationSwHits(TransportersIdentificationSwHits transportersIdentificationSwHits) {
		this.transportersIdentificationSwHits = transportersIdentificationSwHits;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sw_report_id", nullable = false, insertable = false, updatable = false)
	public TransportersIdentificationSwReports getTransportersIdentificationSwReports() {
		return this.transportersIdentificationSwReports;
	}

	public void setTransportersIdentificationSwReports(
			TransportersIdentificationSwReports transportersIdentificationSwReports) {
		this.transportersIdentificationSwReports = transportersIdentificationSwReports;
	}

	@Column(name = "similarity", precision = 12, scale = 0)
	public Float getSimilarity() {
		return this.similarity;
	}

	public void setSimilarity(Float similarity) {
		this.similarity = similarity;
	}

}
