package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransportersAnnotationTransportSystems generated by hbm2java
 */
@Entity
@Table(name="transporters_annotation_transport_systems"
    ,catalog="test_hibernate"
)
public class TransportersAnnotationTransportSystems  implements java.io.Serializable {


     private Integer id;
     private int transportTypeId;
     private Boolean reversible;

    public TransportersAnnotationTransportSystems() {
    }

	
    public TransportersAnnotationTransportSystems(int transportTypeId) {
        this.transportTypeId = transportTypeId;
    }
    public TransportersAnnotationTransportSystems(int transportTypeId, Boolean reversible) {
       this.transportTypeId = transportTypeId;
       this.reversible = reversible;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="transport_type_id", nullable=false)
    public int getTransportTypeId() {
        return this.transportTypeId;
    }
    
    public void setTransportTypeId(int transportTypeId) {
        this.transportTypeId = transportTypeId;
    }

    
    @Column(name="reversible")
    public Boolean getReversible() {
        return this.reversible;
    }
    
    public void setReversible(Boolean reversible) {
        this.reversible = reversible;
    }




}


