package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransportersAnnotationMetabolites generated by hbm2java
 */
@Entity
@Table(name = "transporters_annotation_metabolites", catalog = "sysbio_model")
public class TransportersAnnotationMetabolites implements java.io.Serializable {

	private Integer id;
	private String name;
	private String keggMiriam;
	private String keggName;
	private String chebiMiriam;
	private String chebiName;
	private String datatype;
	private String keggFormula;
	private String chebiFormula;
	private Set<TransportersAnnotationGenesHasMetabolites> transportersAnnotationGenesHasMetaboliteses = new HashSet<TransportersAnnotationGenesHasMetabolites>(
			0);
	private Set<TransportersAnnotationTransportedMetabolitesDirections> transportersAnnotationTransportedMetabolitesDirectionses = new HashSet<TransportersAnnotationTransportedMetabolitesDirections>(
			0);
	private Set<TransportersAnnotationSynonyms> transportersAnnotationSynonymses = new HashSet<TransportersAnnotationSynonyms>(
			0);

	public TransportersAnnotationMetabolites() {
	}

	public TransportersAnnotationMetabolites(String name, String datatype) {
		this.name = name;
		this.datatype = datatype;
	}

	public TransportersAnnotationMetabolites(String name, String keggMiriam, String keggName, String chebiMiriam,
			String chebiName, String datatype, String keggFormula, String chebiFormula,
			Set<TransportersAnnotationGenesHasMetabolites> transportersAnnotationGenesHasMetaboliteses,
			Set<TransportersAnnotationTransportedMetabolitesDirections> transportersAnnotationTransportedMetabolitesDirectionses,
			Set<TransportersAnnotationSynonyms> transportersAnnotationSynonymses) {
		this.name = name;
		this.keggMiriam = keggMiriam;
		this.keggName = keggName;
		this.chebiMiriam = chebiMiriam;
		this.chebiName = chebiName;
		this.datatype = datatype;
		this.keggFormula = keggFormula;
		this.chebiFormula = chebiFormula;
		this.transportersAnnotationGenesHasMetaboliteses = transportersAnnotationGenesHasMetaboliteses;
		this.transportersAnnotationTransportedMetabolitesDirectionses = transportersAnnotationTransportedMetabolitesDirectionses;
		this.transportersAnnotationSynonymses = transportersAnnotationSynonymses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "kegg_miriam", length = 100)
	public String getKeggMiriam() {
		return this.keggMiriam;
	}

	public void setKeggMiriam(String keggMiriam) {
		this.keggMiriam = keggMiriam;
	}

	@Column(name = "kegg_name", length = 500)
	public String getKeggName() {
		return this.keggName;
	}

	public void setKeggName(String keggName) {
		this.keggName = keggName;
	}

	@Column(name = "chebi_miriam", length = 100)
	public String getChebiMiriam() {
		return this.chebiMiriam;
	}

	public void setChebiMiriam(String chebiMiriam) {
		this.chebiMiriam = chebiMiriam;
	}

	@Column(name = "chebi_name", length = 500)
	public String getChebiName() {
		return this.chebiName;
	}

	public void setChebiName(String chebiName) {
		this.chebiName = chebiName;
	}

	@Column(name = "datatype", nullable = false, length = 45)
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "kegg_formula", length = 45)
	public String getKeggFormula() {
		return this.keggFormula;
	}

	public void setKeggFormula(String keggFormula) {
		this.keggFormula = keggFormula;
	}

	@Column(name = "chebi_formula", length = 45)
	public String getChebiFormula() {
		return this.chebiFormula;
	}

	public void setChebiFormula(String chebiFormula) {
		this.chebiFormula = chebiFormula;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationMetabolites")
	public Set<TransportersAnnotationGenesHasMetabolites> getTransportersAnnotationGenesHasMetaboliteses() {
		return this.transportersAnnotationGenesHasMetaboliteses;
	}

	public void setTransportersAnnotationGenesHasMetaboliteses(
			Set<TransportersAnnotationGenesHasMetabolites> transportersAnnotationGenesHasMetaboliteses) {
		this.transportersAnnotationGenesHasMetaboliteses = transportersAnnotationGenesHasMetaboliteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationMetabolites")
	public Set<TransportersAnnotationTransportedMetabolitesDirections> getTransportersAnnotationTransportedMetabolitesDirectionses() {
		return this.transportersAnnotationTransportedMetabolitesDirectionses;
	}

	public void setTransportersAnnotationTransportedMetabolitesDirectionses(
			Set<TransportersAnnotationTransportedMetabolitesDirections> transportersAnnotationTransportedMetabolitesDirectionses) {
		this.transportersAnnotationTransportedMetabolitesDirectionses = transportersAnnotationTransportedMetabolitesDirectionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersAnnotationMetabolites")
	public Set<TransportersAnnotationSynonyms> getTransportersAnnotationSynonymses() {
		return this.transportersAnnotationSynonymses;
	}

	public void setTransportersAnnotationSynonymses(
			Set<TransportersAnnotationSynonyms> transportersAnnotationSynonymses) {
		this.transportersAnnotationSynonymses = transportersAnnotationSynonymses;
	}

}
