package hibernate.merlin_hibernate.entities;
// Generated 4/jun/2018 16:57:32 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransportersAnnotationGeneralEquation generated by hbm2java
 */
@Entity
@Table(name="transporters_annotation_general_equation"
    ,catalog="test_hibernate"
)
public class TransportersAnnotationGeneralEquation  implements java.io.Serializable {


     private Integer id;
     private String equation;

    public TransportersAnnotationGeneralEquation() {
    }

    public TransportersAnnotationGeneralEquation(String equation) {
       this.equation = equation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="equation", length=450)
    public String getEquation() {
        return this.equation;
    }
    
    public void setEquation(String equation) {
        this.equation = equation;
    }




}


