package hibernate.merlin_hibernate.entities;
// Generated 18/mai/2018 12:30:24 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransportersIdentificationSwHits generated by hbm2java
 */
@Entity
@Table(name = "transporters_identification_sw_hits", catalog = "sysbio_model")
public class TransportersIdentificationSwHits implements java.io.Serializable {

	private Integer id;
	private String acc;
	private String tcdbId;
	private Set<TransportersIdentificationSwSimilarities> transportersIdentificationSwSimilaritieses = new HashSet<TransportersIdentificationSwSimilarities>(
			0);

	public TransportersIdentificationSwHits() {
	}

	public TransportersIdentificationSwHits(String acc, String tcdbId) {
		this.acc = acc;
		this.tcdbId = tcdbId;
	}

	public TransportersIdentificationSwHits(String acc, String tcdbId,
			Set<TransportersIdentificationSwSimilarities> transportersIdentificationSwSimilaritieses) {
		this.acc = acc;
		this.tcdbId = tcdbId;
		this.transportersIdentificationSwSimilaritieses = transportersIdentificationSwSimilaritieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "acc", nullable = false, length = 45)
	public String getAcc() {
		return this.acc;
	}

	public void setAcc(String acc) {
		this.acc = acc;
	}

	@Column(name = "tcdb_id", nullable = false, length = 45)
	public String getTcdbId() {
		return this.tcdbId;
	}

	public void setTcdbId(String tcdbId) {
		this.tcdbId = tcdbId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportersIdentificationSwHits")
	public Set<TransportersIdentificationSwSimilarities> getTransportersIdentificationSwSimilaritieses() {
		return this.transportersIdentificationSwSimilaritieses;
	}

	public void setTransportersIdentificationSwSimilaritieses(
			Set<TransportersIdentificationSwSimilarities> transportersIdentificationSwSimilaritieses) {
		this.transportersIdentificationSwSimilaritieses = transportersIdentificationSwSimilaritieses;
	}

}
